/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.inventory.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.inventory.model.CommerceInventoryWarehouseItem;
import com.liferay.commerce.inventory.model.CommerceInventoryWarehouseItemModel;
import com.liferay.commerce.inventory.model.CommerceInventoryWarehouseItemSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CommerceInventoryWarehouseItem service. Represents a row in the &quot;CIWarehouseItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CommerceInventoryWarehouseItemModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceInventoryWarehouseItemImpl}.
 * </p>
 *
 * @author Luca Pellizzon
 * @see CommerceInventoryWarehouseItemImpl
 * @see CommerceInventoryWarehouseItem
 * @see CommerceInventoryWarehouseItemModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CommerceInventoryWarehouseItemModelImpl extends BaseModelImpl<CommerceInventoryWarehouseItem>
	implements CommerceInventoryWarehouseItemModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce inventory warehouse item model instance should use the {@link CommerceInventoryWarehouseItem} interface instead.
	 */
	public static final String TABLE_NAME = "CIWarehouseItem";
	public static final Object[][] TABLE_COLUMNS = {
			{ "CIWarehouseItemId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "commerceWarehouseId", Types.BIGINT },
			{ "sku", Types.VARCHAR },
			{ "quantity", Types.INTEGER },
			{ "reservedQuantity", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("CIWarehouseItemId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("commerceWarehouseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sku", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("quantity", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("reservedQuantity", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table CIWarehouseItem (CIWarehouseItemId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,commerceWarehouseId LONG,sku VARCHAR(75) null,quantity INTEGER,reservedQuantity INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table CIWarehouseItem";
	public static final String ORDER_BY_JPQL = " ORDER BY commerceInventoryWarehouseItem.commerceInventoryWarehouseItemId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CIWarehouseItem.CIWarehouseItemId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.commerce.inventory.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.commerce.inventory.model.CommerceInventoryWarehouseItem"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.commerce.inventory.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.commerce.inventory.model.CommerceInventoryWarehouseItem"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.commerce.inventory.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.commerce.inventory.model.CommerceInventoryWarehouseItem"),
			true);
	public static final long COMMERCEWAREHOUSEID_COLUMN_BITMASK = 1L;
	public static final long SKU_COLUMN_BITMASK = 2L;
	public static final long COMMERCEINVENTORYWAREHOUSEITEMID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CommerceInventoryWarehouseItem toModel(
		CommerceInventoryWarehouseItemSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CommerceInventoryWarehouseItem model = new CommerceInventoryWarehouseItemImpl();

		model.setCommerceInventoryWarehouseItemId(soapModel.getCommerceInventoryWarehouseItemId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCommerceWarehouseId(soapModel.getCommerceWarehouseId());
		model.setSku(soapModel.getSku());
		model.setQuantity(soapModel.getQuantity());
		model.setReservedQuantity(soapModel.getReservedQuantity());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CommerceInventoryWarehouseItem> toModels(
		CommerceInventoryWarehouseItemSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CommerceInventoryWarehouseItem> models = new ArrayList<CommerceInventoryWarehouseItem>(soapModels.length);

		for (CommerceInventoryWarehouseItemSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.commerce.inventory.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.commerce.inventory.model.CommerceInventoryWarehouseItem"));

	public CommerceInventoryWarehouseItemModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commerceInventoryWarehouseItemId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommerceInventoryWarehouseItemId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commerceInventoryWarehouseItemId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommerceInventoryWarehouseItem.class;
	}

	@Override
	public String getModelClassName() {
		return CommerceInventoryWarehouseItem.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("commerceInventoryWarehouseItemId",
			getCommerceInventoryWarehouseItemId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("commerceWarehouseId", getCommerceWarehouseId());
		attributes.put("sku", getSku());
		attributes.put("quantity", getQuantity());
		attributes.put("reservedQuantity", getReservedQuantity());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long commerceInventoryWarehouseItemId = (Long)attributes.get(
				"commerceInventoryWarehouseItemId");

		if (commerceInventoryWarehouseItemId != null) {
			setCommerceInventoryWarehouseItemId(commerceInventoryWarehouseItemId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long commerceWarehouseId = (Long)attributes.get("commerceWarehouseId");

		if (commerceWarehouseId != null) {
			setCommerceWarehouseId(commerceWarehouseId);
		}

		String sku = (String)attributes.get("sku");

		if (sku != null) {
			setSku(sku);
		}

		Integer quantity = (Integer)attributes.get("quantity");

		if (quantity != null) {
			setQuantity(quantity);
		}

		Integer reservedQuantity = (Integer)attributes.get("reservedQuantity");

		if (reservedQuantity != null) {
			setReservedQuantity(reservedQuantity);
		}
	}

	@JSON
	@Override
	public long getCommerceInventoryWarehouseItemId() {
		return _commerceInventoryWarehouseItemId;
	}

	@Override
	public void setCommerceInventoryWarehouseItemId(
		long commerceInventoryWarehouseItemId) {
		_commerceInventoryWarehouseItemId = commerceInventoryWarehouseItemId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCommerceWarehouseId() {
		return _commerceWarehouseId;
	}

	@Override
	public void setCommerceWarehouseId(long commerceWarehouseId) {
		_columnBitmask |= COMMERCEWAREHOUSEID_COLUMN_BITMASK;

		if (!_setOriginalCommerceWarehouseId) {
			_setOriginalCommerceWarehouseId = true;

			_originalCommerceWarehouseId = _commerceWarehouseId;
		}

		_commerceWarehouseId = commerceWarehouseId;
	}

	public long getOriginalCommerceWarehouseId() {
		return _originalCommerceWarehouseId;
	}

	@JSON
	@Override
	public String getSku() {
		if (_sku == null) {
			return "";
		}
		else {
			return _sku;
		}
	}

	@Override
	public void setSku(String sku) {
		_columnBitmask |= SKU_COLUMN_BITMASK;

		if (_originalSku == null) {
			_originalSku = _sku;
		}

		_sku = sku;
	}

	public String getOriginalSku() {
		return GetterUtil.getString(_originalSku);
	}

	@JSON
	@Override
	public int getQuantity() {
		return _quantity;
	}

	@Override
	public void setQuantity(int quantity) {
		_quantity = quantity;
	}

	@JSON
	@Override
	public int getReservedQuantity() {
		return _reservedQuantity;
	}

	@Override
	public void setReservedQuantity(int reservedQuantity) {
		_reservedQuantity = reservedQuantity;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CommerceInventoryWarehouseItem.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommerceInventoryWarehouseItem toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CommerceInventoryWarehouseItem)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommerceInventoryWarehouseItemImpl commerceInventoryWarehouseItemImpl = new CommerceInventoryWarehouseItemImpl();

		commerceInventoryWarehouseItemImpl.setCommerceInventoryWarehouseItemId(getCommerceInventoryWarehouseItemId());
		commerceInventoryWarehouseItemImpl.setCompanyId(getCompanyId());
		commerceInventoryWarehouseItemImpl.setUserId(getUserId());
		commerceInventoryWarehouseItemImpl.setUserName(getUserName());
		commerceInventoryWarehouseItemImpl.setCreateDate(getCreateDate());
		commerceInventoryWarehouseItemImpl.setModifiedDate(getModifiedDate());
		commerceInventoryWarehouseItemImpl.setCommerceWarehouseId(getCommerceWarehouseId());
		commerceInventoryWarehouseItemImpl.setSku(getSku());
		commerceInventoryWarehouseItemImpl.setQuantity(getQuantity());
		commerceInventoryWarehouseItemImpl.setReservedQuantity(getReservedQuantity());

		commerceInventoryWarehouseItemImpl.resetOriginalValues();

		return commerceInventoryWarehouseItemImpl;
	}

	@Override
	public int compareTo(
		CommerceInventoryWarehouseItem commerceInventoryWarehouseItem) {
		long primaryKey = commerceInventoryWarehouseItem.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CommerceInventoryWarehouseItem)) {
			return false;
		}

		CommerceInventoryWarehouseItem commerceInventoryWarehouseItem = (CommerceInventoryWarehouseItem)obj;

		long primaryKey = commerceInventoryWarehouseItem.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CommerceInventoryWarehouseItemModelImpl commerceInventoryWarehouseItemModelImpl =
			this;

		commerceInventoryWarehouseItemModelImpl._setModifiedDate = false;

		commerceInventoryWarehouseItemModelImpl._originalCommerceWarehouseId = commerceInventoryWarehouseItemModelImpl._commerceWarehouseId;

		commerceInventoryWarehouseItemModelImpl._setOriginalCommerceWarehouseId = false;

		commerceInventoryWarehouseItemModelImpl._originalSku = commerceInventoryWarehouseItemModelImpl._sku;

		commerceInventoryWarehouseItemModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CommerceInventoryWarehouseItem> toCacheModel() {
		CommerceInventoryWarehouseItemCacheModel commerceInventoryWarehouseItemCacheModel =
			new CommerceInventoryWarehouseItemCacheModel();

		commerceInventoryWarehouseItemCacheModel.commerceInventoryWarehouseItemId = getCommerceInventoryWarehouseItemId();

		commerceInventoryWarehouseItemCacheModel.companyId = getCompanyId();

		commerceInventoryWarehouseItemCacheModel.userId = getUserId();

		commerceInventoryWarehouseItemCacheModel.userName = getUserName();

		String userName = commerceInventoryWarehouseItemCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commerceInventoryWarehouseItemCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commerceInventoryWarehouseItemCacheModel.createDate = createDate.getTime();
		}
		else {
			commerceInventoryWarehouseItemCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commerceInventoryWarehouseItemCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			commerceInventoryWarehouseItemCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		commerceInventoryWarehouseItemCacheModel.commerceWarehouseId = getCommerceWarehouseId();

		commerceInventoryWarehouseItemCacheModel.sku = getSku();

		String sku = commerceInventoryWarehouseItemCacheModel.sku;

		if ((sku != null) && (sku.length() == 0)) {
			commerceInventoryWarehouseItemCacheModel.sku = null;
		}

		commerceInventoryWarehouseItemCacheModel.quantity = getQuantity();

		commerceInventoryWarehouseItemCacheModel.reservedQuantity = getReservedQuantity();

		return commerceInventoryWarehouseItemCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{commerceInventoryWarehouseItemId=");
		sb.append(getCommerceInventoryWarehouseItemId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", commerceWarehouseId=");
		sb.append(getCommerceWarehouseId());
		sb.append(", sku=");
		sb.append(getSku());
		sb.append(", quantity=");
		sb.append(getQuantity());
		sb.append(", reservedQuantity=");
		sb.append(getReservedQuantity());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.commerce.inventory.model.CommerceInventoryWarehouseItem");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>commerceInventoryWarehouseItemId</column-name><column-value><![CDATA[");
		sb.append(getCommerceInventoryWarehouseItemId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>commerceWarehouseId</column-name><column-value><![CDATA[");
		sb.append(getCommerceWarehouseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sku</column-name><column-value><![CDATA[");
		sb.append(getSku());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>quantity</column-name><column-value><![CDATA[");
		sb.append(getQuantity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>reservedQuantity</column-name><column-value><![CDATA[");
		sb.append(getReservedQuantity());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CommerceInventoryWarehouseItem.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CommerceInventoryWarehouseItem.class, ModelWrapper.class
		};
	private long _commerceInventoryWarehouseItemId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _commerceWarehouseId;
	private long _originalCommerceWarehouseId;
	private boolean _setOriginalCommerceWarehouseId;
	private String _sku;
	private String _originalSku;
	private int _quantity;
	private int _reservedQuantity;
	private long _columnBitmask;
	private CommerceInventoryWarehouseItem _escapedModel;
}