/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.user.segment.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.user.segment.model.CommerceUserSegmentEntry;
import com.liferay.commerce.user.segment.service.CommerceUserSegmentEntryLocalServiceUtil;

/**
 * The extended model base implementation for the CommerceUserSegmentEntry service. Represents a row in the &quot;CommerceUserSegmentEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceUserSegmentEntryImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CommerceUserSegmentEntryImpl
 * @see CommerceUserSegmentEntry
 * @generated
 */
@ProviderType
public abstract class CommerceUserSegmentEntryBaseImpl
	extends CommerceUserSegmentEntryModelImpl
	implements CommerceUserSegmentEntry {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce user segment entry model instance should use the {@link CommerceUserSegmentEntry} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CommerceUserSegmentEntryLocalServiceUtil.addCommerceUserSegmentEntry(this);
		}
		else {
			CommerceUserSegmentEntryLocalServiceUtil.updateCommerceUserSegmentEntry(this);
		}
	}
}