/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.model.CommerceWarehouse;
import com.liferay.commerce.model.CommerceWarehouseModel;
import com.liferay.commerce.model.CommerceWarehouseSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommerceWarehouse service. Represents a row in the &quot;CommerceWarehouse&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CommerceWarehouseModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceWarehouseImpl}.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see CommerceWarehouseImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CommerceWarehouseModelImpl
	extends BaseModelImpl<CommerceWarehouse> implements CommerceWarehouseModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce warehouse model instance should use the <code>CommerceWarehouse</code> interface instead.
	 */
	public static final String TABLE_NAME = "CommerceWarehouse";

	public static final Object[][] TABLE_COLUMNS = {
		{"commerceWarehouseId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"active_", Types.BOOLEAN},
		{"street1", Types.VARCHAR}, {"street2", Types.VARCHAR},
		{"street3", Types.VARCHAR}, {"city", Types.VARCHAR},
		{"zip", Types.VARCHAR}, {"commerceRegionId", Types.BIGINT},
		{"commerceCountryId", Types.BIGINT}, {"latitude", Types.DOUBLE},
		{"longitude", Types.DOUBLE}, {"primary_", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("commerceWarehouseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("street1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("street2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("street3", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("city", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("zip", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("commerceRegionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commerceCountryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("latitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("longitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("primary_", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CommerceWarehouse (commerceWarehouseId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,description VARCHAR(75) null,active_ BOOLEAN,street1 VARCHAR(75) null,street2 VARCHAR(75) null,street3 VARCHAR(75) null,city VARCHAR(75) null,zip VARCHAR(75) null,commerceRegionId LONG,commerceCountryId LONG,latitude DOUBLE,longitude DOUBLE,primary_ BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table CommerceWarehouse";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commerceWarehouse.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CommerceWarehouse.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.commerce.model.CommerceWarehouse"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.commerce.model.CommerceWarehouse"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.commerce.model.CommerceWarehouse"),
		true);

	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	public static final long COMMERCECOUNTRYID_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long PRIMARY_COLUMN_BITMASK = 8L;

	public static final long NAME_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CommerceWarehouse toModel(CommerceWarehouseSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CommerceWarehouse model = new CommerceWarehouseImpl();

		model.setCommerceWarehouseId(soapModel.getCommerceWarehouseId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());
		model.setActive(soapModel.isActive());
		model.setStreet1(soapModel.getStreet1());
		model.setStreet2(soapModel.getStreet2());
		model.setStreet3(soapModel.getStreet3());
		model.setCity(soapModel.getCity());
		model.setZip(soapModel.getZip());
		model.setCommerceRegionId(soapModel.getCommerceRegionId());
		model.setCommerceCountryId(soapModel.getCommerceCountryId());
		model.setLatitude(soapModel.getLatitude());
		model.setLongitude(soapModel.getLongitude());
		model.setPrimary(soapModel.isPrimary());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CommerceWarehouse> toModels(
		CommerceWarehouseSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<CommerceWarehouse> models = new ArrayList<CommerceWarehouse>(
			soapModels.length);

		for (CommerceWarehouseSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.commerce.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.commerce.model.CommerceWarehouse"));

	public CommerceWarehouseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commerceWarehouseId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommerceWarehouseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commerceWarehouseId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommerceWarehouse.class;
	}

	@Override
	public String getModelClassName() {
		return CommerceWarehouse.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommerceWarehouse, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CommerceWarehouse, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceWarehouse, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CommerceWarehouse)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommerceWarehouse, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommerceWarehouse, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommerceWarehouse)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommerceWarehouse, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommerceWarehouse, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<CommerceWarehouse, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CommerceWarehouse, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CommerceWarehouse, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CommerceWarehouse, Object>>();
		Map<String, BiConsumer<CommerceWarehouse, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<CommerceWarehouse, ?>>();

		attributeGetterFunctions.put(
			"commerceWarehouseId",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getCommerceWarehouseId();
				}

			});
		attributeSetterBiConsumers.put(
			"commerceWarehouseId",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse,
					Object commerceWarehouseId) {

					commerceWarehouse.setCommerceWarehouseId(
						(Long)commerceWarehouseId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object groupId) {

					commerceWarehouse.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object companyId) {

					commerceWarehouse.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object userId) {

					commerceWarehouse.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object userName) {

					commerceWarehouse.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object createDate) {

					commerceWarehouse.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object modifiedDate) {

					commerceWarehouse.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object name) {

					commerceWarehouse.setName((String)name);
				}

			});
		attributeGetterFunctions.put(
			"description",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getDescription();
				}

			});
		attributeSetterBiConsumers.put(
			"description",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object description) {

					commerceWarehouse.setDescription((String)description);
				}

			});
		attributeGetterFunctions.put(
			"active",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getActive();
				}

			});
		attributeSetterBiConsumers.put(
			"active",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object active) {

					commerceWarehouse.setActive((Boolean)active);
				}

			});
		attributeGetterFunctions.put(
			"street1",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getStreet1();
				}

			});
		attributeSetterBiConsumers.put(
			"street1",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object street1) {

					commerceWarehouse.setStreet1((String)street1);
				}

			});
		attributeGetterFunctions.put(
			"street2",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getStreet2();
				}

			});
		attributeSetterBiConsumers.put(
			"street2",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object street2) {

					commerceWarehouse.setStreet2((String)street2);
				}

			});
		attributeGetterFunctions.put(
			"street3",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getStreet3();
				}

			});
		attributeSetterBiConsumers.put(
			"street3",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object street3) {

					commerceWarehouse.setStreet3((String)street3);
				}

			});
		attributeGetterFunctions.put(
			"city",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getCity();
				}

			});
		attributeSetterBiConsumers.put(
			"city",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object city) {

					commerceWarehouse.setCity((String)city);
				}

			});
		attributeGetterFunctions.put(
			"zip",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getZip();
				}

			});
		attributeSetterBiConsumers.put(
			"zip",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object zip) {

					commerceWarehouse.setZip((String)zip);
				}

			});
		attributeGetterFunctions.put(
			"commerceRegionId",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getCommerceRegionId();
				}

			});
		attributeSetterBiConsumers.put(
			"commerceRegionId",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse,
					Object commerceRegionId) {

					commerceWarehouse.setCommerceRegionId(
						(Long)commerceRegionId);
				}

			});
		attributeGetterFunctions.put(
			"commerceCountryId",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getCommerceCountryId();
				}

			});
		attributeSetterBiConsumers.put(
			"commerceCountryId",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse,
					Object commerceCountryId) {

					commerceWarehouse.setCommerceCountryId(
						(Long)commerceCountryId);
				}

			});
		attributeGetterFunctions.put(
			"latitude",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getLatitude();
				}

			});
		attributeSetterBiConsumers.put(
			"latitude",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object latitude) {

					commerceWarehouse.setLatitude((Double)latitude);
				}

			});
		attributeGetterFunctions.put(
			"longitude",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getLongitude();
				}

			});
		attributeSetterBiConsumers.put(
			"longitude",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object longitude) {

					commerceWarehouse.setLongitude((Double)longitude);
				}

			});
		attributeGetterFunctions.put(
			"primary",
			new Function<CommerceWarehouse, Object>() {

				@Override
				public Object apply(CommerceWarehouse commerceWarehouse) {
					return commerceWarehouse.getPrimary();
				}

			});
		attributeSetterBiConsumers.put(
			"primary",
			new BiConsumer<CommerceWarehouse, Object>() {

				@Override
				public void accept(
					CommerceWarehouse commerceWarehouse, Object primary) {

					commerceWarehouse.setPrimary((Boolean)primary);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getCommerceWarehouseId() {
		return _commerceWarehouseId;
	}

	@Override
	public void setCommerceWarehouseId(long commerceWarehouseId) {
		_commerceWarehouseId = commerceWarehouseId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		_name = name;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	@JSON
	@Override
	public String getStreet1() {
		if (_street1 == null) {
			return "";
		}
		else {
			return _street1;
		}
	}

	@Override
	public void setStreet1(String street1) {
		_street1 = street1;
	}

	@JSON
	@Override
	public String getStreet2() {
		if (_street2 == null) {
			return "";
		}
		else {
			return _street2;
		}
	}

	@Override
	public void setStreet2(String street2) {
		_street2 = street2;
	}

	@JSON
	@Override
	public String getStreet3() {
		if (_street3 == null) {
			return "";
		}
		else {
			return _street3;
		}
	}

	@Override
	public void setStreet3(String street3) {
		_street3 = street3;
	}

	@JSON
	@Override
	public String getCity() {
		if (_city == null) {
			return "";
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		_city = city;
	}

	@JSON
	@Override
	public String getZip() {
		if (_zip == null) {
			return "";
		}
		else {
			return _zip;
		}
	}

	@Override
	public void setZip(String zip) {
		_zip = zip;
	}

	@JSON
	@Override
	public long getCommerceRegionId() {
		return _commerceRegionId;
	}

	@Override
	public void setCommerceRegionId(long commerceRegionId) {
		_commerceRegionId = commerceRegionId;
	}

	@JSON
	@Override
	public long getCommerceCountryId() {
		return _commerceCountryId;
	}

	@Override
	public void setCommerceCountryId(long commerceCountryId) {
		_columnBitmask |= COMMERCECOUNTRYID_COLUMN_BITMASK;

		if (!_setOriginalCommerceCountryId) {
			_setOriginalCommerceCountryId = true;

			_originalCommerceCountryId = _commerceCountryId;
		}

		_commerceCountryId = commerceCountryId;
	}

	public long getOriginalCommerceCountryId() {
		return _originalCommerceCountryId;
	}

	@JSON
	@Override
	public double getLatitude() {
		return _latitude;
	}

	@Override
	public void setLatitude(double latitude) {
		_latitude = latitude;
	}

	@JSON
	@Override
	public double getLongitude() {
		return _longitude;
	}

	@Override
	public void setLongitude(double longitude) {
		_longitude = longitude;
	}

	@JSON
	@Override
	public boolean getPrimary() {
		return _primary;
	}

	@JSON
	@Override
	public boolean isPrimary() {
		return _primary;
	}

	@Override
	public void setPrimary(boolean primary) {
		_columnBitmask |= PRIMARY_COLUMN_BITMASK;

		if (!_setOriginalPrimary) {
			_setOriginalPrimary = true;

			_originalPrimary = _primary;
		}

		_primary = primary;
	}

	public boolean getOriginalPrimary() {
		return _originalPrimary;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CommerceWarehouse.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommerceWarehouse toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CommerceWarehouse)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommerceWarehouseImpl commerceWarehouseImpl =
			new CommerceWarehouseImpl();

		commerceWarehouseImpl.setCommerceWarehouseId(getCommerceWarehouseId());
		commerceWarehouseImpl.setGroupId(getGroupId());
		commerceWarehouseImpl.setCompanyId(getCompanyId());
		commerceWarehouseImpl.setUserId(getUserId());
		commerceWarehouseImpl.setUserName(getUserName());
		commerceWarehouseImpl.setCreateDate(getCreateDate());
		commerceWarehouseImpl.setModifiedDate(getModifiedDate());
		commerceWarehouseImpl.setName(getName());
		commerceWarehouseImpl.setDescription(getDescription());
		commerceWarehouseImpl.setActive(isActive());
		commerceWarehouseImpl.setStreet1(getStreet1());
		commerceWarehouseImpl.setStreet2(getStreet2());
		commerceWarehouseImpl.setStreet3(getStreet3());
		commerceWarehouseImpl.setCity(getCity());
		commerceWarehouseImpl.setZip(getZip());
		commerceWarehouseImpl.setCommerceRegionId(getCommerceRegionId());
		commerceWarehouseImpl.setCommerceCountryId(getCommerceCountryId());
		commerceWarehouseImpl.setLatitude(getLatitude());
		commerceWarehouseImpl.setLongitude(getLongitude());
		commerceWarehouseImpl.setPrimary(isPrimary());

		commerceWarehouseImpl.resetOriginalValues();

		return commerceWarehouseImpl;
	}

	@Override
	public int compareTo(CommerceWarehouse commerceWarehouse) {
		int value = 0;

		value = getName().compareTo(commerceWarehouse.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CommerceWarehouse)) {
			return false;
		}

		CommerceWarehouse commerceWarehouse = (CommerceWarehouse)obj;

		long primaryKey = commerceWarehouse.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CommerceWarehouseModelImpl commerceWarehouseModelImpl = this;

		commerceWarehouseModelImpl._originalGroupId =
			commerceWarehouseModelImpl._groupId;

		commerceWarehouseModelImpl._setOriginalGroupId = false;

		commerceWarehouseModelImpl._setModifiedDate = false;

		commerceWarehouseModelImpl._originalActive =
			commerceWarehouseModelImpl._active;

		commerceWarehouseModelImpl._setOriginalActive = false;

		commerceWarehouseModelImpl._originalCommerceCountryId =
			commerceWarehouseModelImpl._commerceCountryId;

		commerceWarehouseModelImpl._setOriginalCommerceCountryId = false;

		commerceWarehouseModelImpl._originalPrimary =
			commerceWarehouseModelImpl._primary;

		commerceWarehouseModelImpl._setOriginalPrimary = false;

		commerceWarehouseModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CommerceWarehouse> toCacheModel() {
		CommerceWarehouseCacheModel commerceWarehouseCacheModel =
			new CommerceWarehouseCacheModel();

		commerceWarehouseCacheModel.commerceWarehouseId =
			getCommerceWarehouseId();

		commerceWarehouseCacheModel.groupId = getGroupId();

		commerceWarehouseCacheModel.companyId = getCompanyId();

		commerceWarehouseCacheModel.userId = getUserId();

		commerceWarehouseCacheModel.userName = getUserName();

		String userName = commerceWarehouseCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commerceWarehouseCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commerceWarehouseCacheModel.createDate = createDate.getTime();
		}
		else {
			commerceWarehouseCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commerceWarehouseCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			commerceWarehouseCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		commerceWarehouseCacheModel.name = getName();

		String name = commerceWarehouseCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			commerceWarehouseCacheModel.name = null;
		}

		commerceWarehouseCacheModel.description = getDescription();

		String description = commerceWarehouseCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			commerceWarehouseCacheModel.description = null;
		}

		commerceWarehouseCacheModel.active = isActive();

		commerceWarehouseCacheModel.street1 = getStreet1();

		String street1 = commerceWarehouseCacheModel.street1;

		if ((street1 != null) && (street1.length() == 0)) {
			commerceWarehouseCacheModel.street1 = null;
		}

		commerceWarehouseCacheModel.street2 = getStreet2();

		String street2 = commerceWarehouseCacheModel.street2;

		if ((street2 != null) && (street2.length() == 0)) {
			commerceWarehouseCacheModel.street2 = null;
		}

		commerceWarehouseCacheModel.street3 = getStreet3();

		String street3 = commerceWarehouseCacheModel.street3;

		if ((street3 != null) && (street3.length() == 0)) {
			commerceWarehouseCacheModel.street3 = null;
		}

		commerceWarehouseCacheModel.city = getCity();

		String city = commerceWarehouseCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			commerceWarehouseCacheModel.city = null;
		}

		commerceWarehouseCacheModel.zip = getZip();

		String zip = commerceWarehouseCacheModel.zip;

		if ((zip != null) && (zip.length() == 0)) {
			commerceWarehouseCacheModel.zip = null;
		}

		commerceWarehouseCacheModel.commerceRegionId = getCommerceRegionId();

		commerceWarehouseCacheModel.commerceCountryId = getCommerceCountryId();

		commerceWarehouseCacheModel.latitude = getLatitude();

		commerceWarehouseCacheModel.longitude = getLongitude();

		commerceWarehouseCacheModel.primary = isPrimary();

		return commerceWarehouseCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommerceWarehouse, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CommerceWarehouse, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceWarehouse, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CommerceWarehouse)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CommerceWarehouse, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CommerceWarehouse, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceWarehouse, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CommerceWarehouse)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		CommerceWarehouse.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		CommerceWarehouse.class, ModelWrapper.class
	};

	private long _commerceWarehouseId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _description;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private String _street1;
	private String _street2;
	private String _street3;
	private String _city;
	private String _zip;
	private long _commerceRegionId;
	private long _commerceCountryId;
	private long _originalCommerceCountryId;
	private boolean _setOriginalCommerceCountryId;
	private double _latitude;
	private double _longitude;
	private boolean _primary;
	private boolean _originalPrimary;
	private boolean _setOriginalPrimary;
	private long _columnBitmask;
	private CommerceWarehouse _escapedModel;

}