/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.data.integration.manager.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.data.integration.manager.model.History;
import com.liferay.commerce.data.integration.manager.model.impl.HistoryModelImpl;
import com.liferay.commerce.data.integration.manager.service.HistoryLocalService;
import com.liferay.commerce.data.integration.manager.service.HistoryLocalServiceUtil;
import com.liferay.commerce.data.integration.manager.service.ProcessLocalService;
import com.liferay.commerce.data.integration.manager.service.ScheduledTaskLocalService;
import com.liferay.commerce.data.integration.manager.service.impl.HistoryLocalServiceImpl;
import com.liferay.commerce.data.integration.manager.service.persistence.HistoryPersistence;
import com.liferay.commerce.data.integration.manager.service.persistence.ProcessPersistence;
import com.liferay.commerce.data.integration.manager.service.persistence.ScheduledTaskPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the history local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link HistoryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HistoryLocalServiceImpl
 * @see HistoryLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class HistoryLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements HistoryLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.data.integration.service.HistoryLocalServiceUtil} to access the history local service.
	 */

	/**
	 * Adds the history to the database. Also notifies the appropriate model listeners.
	 *
	 * @param history the history
	 * @return the history that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public History addHistory(History history) {
		history.setNew(true);

		return historyPersistence.update(history);
	}

	/**
	 * Creates a new history with the primary key. Does not add the history to the database.
	 *
	 * @param historyId the primary key for the new history
	 * @return the new history
	 */
	@Override
	@Transactional(enabled = false)
	public History createHistory(long historyId) {
		return historyPersistence.create(historyId);
	}

	/**
	 * Deletes the history with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param historyId the primary key of the history
	 * @return the history that was removed
	 * @throws PortalException if a history with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public History deleteHistory(long historyId) throws PortalException {
		return historyPersistence.remove(historyId);
	}

	/**
	 * Deletes the history from the database. Also notifies the appropriate model listeners.
	 *
	 * @param history the history
	 * @return the history that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public History deleteHistory(History history) {
		return historyPersistence.remove(history);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(History.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return historyPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link HistoryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return historyPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link HistoryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return historyPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return historyPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return historyPersistence.countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public History fetchHistory(long historyId) {
		return historyPersistence.fetchByPrimaryKey(historyId);
	}

	/**
	 * Returns the history matching the UUID and group.
	 *
	 * @param uuid the history's UUID
	 * @param groupId the primary key of the group
	 * @return the matching history, or <code>null</code> if a matching history could not be found
	 */
	@Override
	public History fetchHistoryByUuidAndGroupId(String uuid, long groupId) {
		return historyPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the history with the primary key.
	 *
	 * @param historyId the primary key of the history
	 * @return the history
	 * @throws PortalException if a history with the primary key could not be found
	 */
	@Override
	public History getHistory(long historyId) throws PortalException {
		return historyPersistence.findByPrimaryKey(historyId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(historyLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(History.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("historyId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(historyLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(History.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("historyId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(historyLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(History.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("historyId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {
		final ExportActionableDynamicQuery exportActionableDynamicQuery = new ExportActionableDynamicQuery() {
				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary = portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(stagedModelType,
						modelAdditionCount);

					long modelDeletionCount = ExportImportHelperUtil.getModelDeletionCount(portletDataContext,
							stagedModelType);

					manifestSummary.addModelDeletionCount(stagedModelType,
						modelDeletionCount);

					return modelAdditionCount;
				}
			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(new ActionableDynamicQuery.AddCriteriaMethod() {
				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(dynamicQuery,
						"modifiedDate");
				}
			});

		exportActionableDynamicQuery.setCompanyId(portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(new ActionableDynamicQuery.PerformActionMethod<History>() {
				@Override
				public void performAction(History history)
					throws PortalException {
					StagedModelDataHandlerUtil.exportStagedModel(portletDataContext,
						history);
				}
			});
		exportActionableDynamicQuery.setStagedModelType(new StagedModelType(
				PortalUtil.getClassNameId(History.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return historyLocalService.deleteHistory((History)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return historyPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the histories matching the UUID and company.
	 *
	 * @param uuid the UUID of the histories
	 * @param companyId the primary key of the company
	 * @return the matching histories, or an empty list if no matches were found
	 */
	@Override
	public List<History> getHistoriesByUuidAndCompanyId(String uuid,
		long companyId) {
		return historyPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of histories matching the UUID and company.
	 *
	 * @param uuid the UUID of the histories
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of histories
	 * @param end the upper bound of the range of histories (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching histories, or an empty list if no matches were found
	 */
	@Override
	public List<History> getHistoriesByUuidAndCompanyId(String uuid,
		long companyId, int start, int end,
		OrderByComparator<History> orderByComparator) {
		return historyPersistence.findByUuid_C(uuid, companyId, start, end,
			orderByComparator);
	}

	/**
	 * Returns the history matching the UUID and group.
	 *
	 * @param uuid the history's UUID
	 * @param groupId the primary key of the group
	 * @return the matching history
	 * @throws PortalException if a matching history could not be found
	 */
	@Override
	public History getHistoryByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {
		return historyPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the histories.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link HistoryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of histories
	 * @param end the upper bound of the range of histories (not inclusive)
	 * @return the range of histories
	 */
	@Override
	public List<History> getHistories(int start, int end) {
		return historyPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of histories.
	 *
	 * @return the number of histories
	 */
	@Override
	public int getHistoriesCount() {
		return historyPersistence.countAll();
	}

	/**
	 * Updates the history in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param history the history
	 * @return the history that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public History updateHistory(History history) {
		return historyPersistence.update(history);
	}

	/**
	 * Returns the history local service.
	 *
	 * @return the history local service
	 */
	public HistoryLocalService getHistoryLocalService() {
		return historyLocalService;
	}

	/**
	 * Sets the history local service.
	 *
	 * @param historyLocalService the history local service
	 */
	public void setHistoryLocalService(HistoryLocalService historyLocalService) {
		this.historyLocalService = historyLocalService;
	}

	/**
	 * Returns the history persistence.
	 *
	 * @return the history persistence
	 */
	public HistoryPersistence getHistoryPersistence() {
		return historyPersistence;
	}

	/**
	 * Sets the history persistence.
	 *
	 * @param historyPersistence the history persistence
	 */
	public void setHistoryPersistence(HistoryPersistence historyPersistence) {
		this.historyPersistence = historyPersistence;
	}

	/**
	 * Returns the process local service.
	 *
	 * @return the process local service
	 */
	public ProcessLocalService getProcessLocalService() {
		return processLocalService;
	}

	/**
	 * Sets the process local service.
	 *
	 * @param processLocalService the process local service
	 */
	public void setProcessLocalService(
		ProcessLocalService processLocalService) {
		this.processLocalService = processLocalService;
	}

	/**
	 * Returns the process persistence.
	 *
	 * @return the process persistence
	 */
	public ProcessPersistence getProcessPersistence() {
		return processPersistence;
	}

	/**
	 * Sets the process persistence.
	 *
	 * @param processPersistence the process persistence
	 */
	public void setProcessPersistence(ProcessPersistence processPersistence) {
		this.processPersistence = processPersistence;
	}

	/**
	 * Returns the scheduled task local service.
	 *
	 * @return the scheduled task local service
	 */
	public ScheduledTaskLocalService getScheduledTaskLocalService() {
		return scheduledTaskLocalService;
	}

	/**
	 * Sets the scheduled task local service.
	 *
	 * @param scheduledTaskLocalService the scheduled task local service
	 */
	public void setScheduledTaskLocalService(
		ScheduledTaskLocalService scheduledTaskLocalService) {
		this.scheduledTaskLocalService = scheduledTaskLocalService;
	}

	/**
	 * Returns the scheduled task persistence.
	 *
	 * @return the scheduled task persistence
	 */
	public ScheduledTaskPersistence getScheduledTaskPersistence() {
		return scheduledTaskPersistence;
	}

	/**
	 * Sets the scheduled task persistence.
	 *
	 * @param scheduledTaskPersistence the scheduled task persistence
	 */
	public void setScheduledTaskPersistence(
		ScheduledTaskPersistence scheduledTaskPersistence) {
		this.scheduledTaskPersistence = scheduledTaskPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.data.integration.model.History",
			historyLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.data.integration.model.History");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return HistoryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return History.class;
	}

	protected String getModelClassName() {
		return History.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = historyPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = HistoryLocalService.class)
	protected HistoryLocalService historyLocalService;
	@BeanReference(type = HistoryPersistence.class)
	protected HistoryPersistence historyPersistence;
	@BeanReference(type = ProcessLocalService.class)
	protected ProcessLocalService processLocalService;
	@BeanReference(type = ProcessPersistence.class)
	protected ProcessPersistence processPersistence;
	@BeanReference(type = ScheduledTaskLocalService.class)
	protected ScheduledTaskLocalService scheduledTaskLocalService;
	@BeanReference(type = ScheduledTaskPersistence.class)
	protected ScheduledTaskPersistence scheduledTaskPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}