/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CommerceShipmentItem service. Represents a row in the &quot;CommerceShipmentItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.commerce.model.impl.CommerceShipmentItemModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.commerce.model.impl.CommerceShipmentItemImpl</code>.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see CommerceShipmentItem
 * @generated
 */
@ProviderType
public interface CommerceShipmentItemModel
	extends BaseModel<CommerceShipmentItem>, GroupedModel, ShardedModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commerce shipment item model instance should use the {@link CommerceShipmentItem} interface instead.
	 */

	/**
	 * Returns the primary key of this commerce shipment item.
	 *
	 * @return the primary key of this commerce shipment item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commerce shipment item.
	 *
	 * @param primaryKey the primary key of this commerce shipment item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the commerce shipment item ID of this commerce shipment item.
	 *
	 * @return the commerce shipment item ID of this commerce shipment item
	 */
	public long getCommerceShipmentItemId();

	/**
	 * Sets the commerce shipment item ID of this commerce shipment item.
	 *
	 * @param commerceShipmentItemId the commerce shipment item ID of this commerce shipment item
	 */
	public void setCommerceShipmentItemId(long commerceShipmentItemId);

	/**
	 * Returns the group ID of this commerce shipment item.
	 *
	 * @return the group ID of this commerce shipment item
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this commerce shipment item.
	 *
	 * @param groupId the group ID of this commerce shipment item
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this commerce shipment item.
	 *
	 * @return the company ID of this commerce shipment item
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commerce shipment item.
	 *
	 * @param companyId the company ID of this commerce shipment item
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this commerce shipment item.
	 *
	 * @return the user ID of this commerce shipment item
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this commerce shipment item.
	 *
	 * @param userId the user ID of this commerce shipment item
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this commerce shipment item.
	 *
	 * @return the user uuid of this commerce shipment item
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this commerce shipment item.
	 *
	 * @param userUuid the user uuid of this commerce shipment item
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this commerce shipment item.
	 *
	 * @return the user name of this commerce shipment item
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this commerce shipment item.
	 *
	 * @param userName the user name of this commerce shipment item
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this commerce shipment item.
	 *
	 * @return the create date of this commerce shipment item
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this commerce shipment item.
	 *
	 * @param createDate the create date of this commerce shipment item
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this commerce shipment item.
	 *
	 * @return the modified date of this commerce shipment item
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this commerce shipment item.
	 *
	 * @param modifiedDate the modified date of this commerce shipment item
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the commerce shipment ID of this commerce shipment item.
	 *
	 * @return the commerce shipment ID of this commerce shipment item
	 */
	public long getCommerceShipmentId();

	/**
	 * Sets the commerce shipment ID of this commerce shipment item.
	 *
	 * @param commerceShipmentId the commerce shipment ID of this commerce shipment item
	 */
	public void setCommerceShipmentId(long commerceShipmentId);

	/**
	 * Returns the commerce order item ID of this commerce shipment item.
	 *
	 * @return the commerce order item ID of this commerce shipment item
	 */
	public long getCommerceOrderItemId();

	/**
	 * Sets the commerce order item ID of this commerce shipment item.
	 *
	 * @param commerceOrderItemId the commerce order item ID of this commerce shipment item
	 */
	public void setCommerceOrderItemId(long commerceOrderItemId);

	/**
	 * Returns the commerce inventory warehouse ID of this commerce shipment item.
	 *
	 * @return the commerce inventory warehouse ID of this commerce shipment item
	 */
	public long getCommerceInventoryWarehouseId();

	/**
	 * Sets the commerce inventory warehouse ID of this commerce shipment item.
	 *
	 * @param commerceInventoryWarehouseId the commerce inventory warehouse ID of this commerce shipment item
	 */
	public void setCommerceInventoryWarehouseId(
		long commerceInventoryWarehouseId);

	/**
	 * Returns the quantity of this commerce shipment item.
	 *
	 * @return the quantity of this commerce shipment item
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this commerce shipment item.
	 *
	 * @param quantity the quantity of this commerce shipment item
	 */
	public void setQuantity(int quantity);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CommerceShipmentItem commerceShipmentItem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CommerceShipmentItem> toCacheModel();

	@Override
	public CommerceShipmentItem toEscapedModel();

	@Override
	public CommerceShipmentItem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}