/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.batch.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CommerceBatchJobInstance service. Represents a row in the &quot;CommerceBatchJobInstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.commerce.batch.model.impl.CommerceBatchJobInstanceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.commerce.batch.model.impl.CommerceBatchJobInstanceImpl}.
 * </p>
 *
 * @author Matija Petanjek
 * @see CommerceBatchJobInstance
 * @see com.liferay.commerce.batch.model.impl.CommerceBatchJobInstanceImpl
 * @see com.liferay.commerce.batch.model.impl.CommerceBatchJobInstanceModelImpl
 * @generated
 */
@ProviderType
public interface CommerceBatchJobInstanceModel extends BaseModel<CommerceBatchJobInstance> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commerce batch job instance model instance should use the {@link CommerceBatchJobInstance} interface instead.
	 */

	/**
	 * Returns the primary key of this commerce batch job instance.
	 *
	 * @return the primary key of this commerce batch job instance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commerce batch job instance.
	 *
	 * @param primaryKey the primary key of this commerce batch job instance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the commerce batch job instance ID of this commerce batch job instance.
	 *
	 * @return the commerce batch job instance ID of this commerce batch job instance
	 */
	public long getCommerceBatchJobInstanceId();

	/**
	 * Sets the commerce batch job instance ID of this commerce batch job instance.
	 *
	 * @param commerceBatchJobInstanceId the commerce batch job instance ID of this commerce batch job instance
	 */
	public void setCommerceBatchJobInstanceId(long commerceBatchJobInstanceId);

	/**
	 * Returns the create date of this commerce batch job instance.
	 *
	 * @return the create date of this commerce batch job instance
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this commerce batch job instance.
	 *
	 * @param createDate the create date of this commerce batch job instance
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this commerce batch job instance.
	 *
	 * @return the modified date of this commerce batch job instance
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this commerce batch job instance.
	 *
	 * @param modifiedDate the modified date of this commerce batch job instance
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the batch job name of this commerce batch job instance.
	 *
	 * @return the batch job name of this commerce batch job instance
	 */
	@AutoEscape
	public String getBatchJobName();

	/**
	 * Sets the batch job name of this commerce batch job instance.
	 *
	 * @param batchJobName the batch job name of this commerce batch job instance
	 */
	public void setBatchJobName(String batchJobName);

	/**
	 * Returns the key of this commerce batch job instance.
	 *
	 * @return the key of this commerce batch job instance
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this commerce batch job instance.
	 *
	 * @param key the key of this commerce batch job instance
	 */
	public void setKey(String key);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CommerceBatchJobInstance commerceBatchJobInstance);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CommerceBatchJobInstance> toCacheModel();

	@Override
	public CommerceBatchJobInstance toEscapedModel();

	@Override
	public CommerceBatchJobInstance toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}