/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.notification.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CommerceNotificationTemplateUserSegmentRel service. Represents a row in the &quot;CNTemplateUserSegmentRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.commerce.notification.model.impl.CommerceNotificationTemplateUserSegmentRelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.commerce.notification.model.impl.CommerceNotificationTemplateUserSegmentRelImpl}.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see CommerceNotificationTemplateUserSegmentRel
 * @see com.liferay.commerce.notification.model.impl.CommerceNotificationTemplateUserSegmentRelImpl
 * @see com.liferay.commerce.notification.model.impl.CommerceNotificationTemplateUserSegmentRelModelImpl
 * @generated
 */
@ProviderType
public interface CommerceNotificationTemplateUserSegmentRelModel
	extends BaseModel<CommerceNotificationTemplateUserSegmentRel>, GroupedModel,
		ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commerce notification template user segment rel model instance should use the {@link CommerceNotificationTemplateUserSegmentRel} interface instead.
	 */

	/**
	 * Returns the primary key of this commerce notification template user segment rel.
	 *
	 * @return the primary key of this commerce notification template user segment rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commerce notification template user segment rel.
	 *
	 * @param primaryKey the primary key of this commerce notification template user segment rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the commerce notification template user segment rel ID of this commerce notification template user segment rel.
	 *
	 * @return the commerce notification template user segment rel ID of this commerce notification template user segment rel
	 */
	public long getCommerceNotificationTemplateUserSegmentRelId();

	/**
	 * Sets the commerce notification template user segment rel ID of this commerce notification template user segment rel.
	 *
	 * @param commerceNotificationTemplateUserSegmentRelId the commerce notification template user segment rel ID of this commerce notification template user segment rel
	 */
	public void setCommerceNotificationTemplateUserSegmentRelId(
		long commerceNotificationTemplateUserSegmentRelId);

	/**
	 * Returns the group ID of this commerce notification template user segment rel.
	 *
	 * @return the group ID of this commerce notification template user segment rel
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this commerce notification template user segment rel.
	 *
	 * @param groupId the group ID of this commerce notification template user segment rel
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this commerce notification template user segment rel.
	 *
	 * @return the company ID of this commerce notification template user segment rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commerce notification template user segment rel.
	 *
	 * @param companyId the company ID of this commerce notification template user segment rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this commerce notification template user segment rel.
	 *
	 * @return the user ID of this commerce notification template user segment rel
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this commerce notification template user segment rel.
	 *
	 * @param userId the user ID of this commerce notification template user segment rel
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this commerce notification template user segment rel.
	 *
	 * @return the user uuid of this commerce notification template user segment rel
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this commerce notification template user segment rel.
	 *
	 * @param userUuid the user uuid of this commerce notification template user segment rel
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this commerce notification template user segment rel.
	 *
	 * @return the user name of this commerce notification template user segment rel
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this commerce notification template user segment rel.
	 *
	 * @param userName the user name of this commerce notification template user segment rel
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this commerce notification template user segment rel.
	 *
	 * @return the create date of this commerce notification template user segment rel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this commerce notification template user segment rel.
	 *
	 * @param createDate the create date of this commerce notification template user segment rel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this commerce notification template user segment rel.
	 *
	 * @return the modified date of this commerce notification template user segment rel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this commerce notification template user segment rel.
	 *
	 * @param modifiedDate the modified date of this commerce notification template user segment rel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the commerce notification template ID of this commerce notification template user segment rel.
	 *
	 * @return the commerce notification template ID of this commerce notification template user segment rel
	 */
	public long getCommerceNotificationTemplateId();

	/**
	 * Sets the commerce notification template ID of this commerce notification template user segment rel.
	 *
	 * @param commerceNotificationTemplateId the commerce notification template ID of this commerce notification template user segment rel
	 */
	public void setCommerceNotificationTemplateId(
		long commerceNotificationTemplateId);

	/**
	 * Returns the commerce user segment entry ID of this commerce notification template user segment rel.
	 *
	 * @return the commerce user segment entry ID of this commerce notification template user segment rel
	 */
	public long getCommerceUserSegmentEntryId();

	/**
	 * Sets the commerce user segment entry ID of this commerce notification template user segment rel.
	 *
	 * @param commerceUserSegmentEntryId the commerce user segment entry ID of this commerce notification template user segment rel
	 */
	public void setCommerceUserSegmentEntryId(long commerceUserSegmentEntryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		CommerceNotificationTemplateUserSegmentRel commerceNotificationTemplateUserSegmentRel);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CommerceNotificationTemplateUserSegmentRel> toCacheModel();

	@Override
	public CommerceNotificationTemplateUserSegmentRel toEscapedModel();

	@Override
	public CommerceNotificationTemplateUserSegmentRel toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}