/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.product.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.product.model.CPDefinition;
import com.liferay.commerce.product.model.CPDefinitionLocalization;
import com.liferay.commerce.product.model.CPDefinitionModel;
import com.liferay.commerce.product.model.CPDefinitionSoap;
import com.liferay.commerce.product.service.CPDefinitionLocalServiceUtil;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.petra.string.StringBundler;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

/**
 * The base model implementation for the CPDefinition service. Represents a row in the &quot;CPDefinition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CPDefinitionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPDefinitionImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CPDefinitionImpl
 * @see CPDefinition
 * @see CPDefinitionModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CPDefinitionModelImpl extends BaseModelImpl<CPDefinition>
	implements CPDefinitionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cp definition model instance should use the {@link CPDefinition} interface instead.
	 */
	public static final String TABLE_NAME = "CPDefinition";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "externalReferenceCode", Types.VARCHAR },
			{ "defaultLanguageId", Types.VARCHAR },
			{ "CPDefinitionId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "productTypeName", Types.VARCHAR },
			{ "availableIndividually", Types.BOOLEAN },
			{ "ignoreSKUCombinations", Types.BOOLEAN },
			{ "shippable", Types.BOOLEAN },
			{ "freeShipping", Types.BOOLEAN },
			{ "shipSeparately", Types.BOOLEAN },
			{ "shippingExtraPrice", Types.DOUBLE },
			{ "width", Types.DOUBLE },
			{ "height", Types.DOUBLE },
			{ "depth", Types.DOUBLE },
			{ "weight", Types.DOUBLE },
			{ "CPTaxCategoryId", Types.BIGINT },
			{ "taxExempt", Types.BOOLEAN },
			{ "telcoOrElectronics", Types.BOOLEAN },
			{ "DDMStructureKey", Types.VARCHAR },
			{ "published", Types.BOOLEAN },
			{ "displayDate", Types.TIMESTAMP },
			{ "expirationDate", Types.TIMESTAMP },
			{ "lastPublishDate", Types.TIMESTAMP },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("defaultLanguageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CPDefinitionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("productTypeName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("availableIndividually", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("ignoreSKUCombinations", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("shippable", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("freeShipping", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("shipSeparately", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("shippingExtraPrice", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("width", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("height", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("depth", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("weight", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("CPTaxCategoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("taxExempt", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("telcoOrElectronics", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("DDMStructureKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("published", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("displayDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expirationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table CPDefinition (uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,defaultLanguageId VARCHAR(75) null,CPDefinitionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,productTypeName VARCHAR(75) null,availableIndividually BOOLEAN,ignoreSKUCombinations BOOLEAN,shippable BOOLEAN,freeShipping BOOLEAN,shipSeparately BOOLEAN,shippingExtraPrice DOUBLE,width DOUBLE,height DOUBLE,depth DOUBLE,weight DOUBLE,CPTaxCategoryId LONG,taxExempt BOOLEAN,telcoOrElectronics BOOLEAN,DDMStructureKey VARCHAR(75) null,published BOOLEAN,displayDate DATE null,expirationDate DATE null,lastPublishDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table CPDefinition";
	public static final String ORDER_BY_JPQL = " ORDER BY cpDefinition.displayDate DESC, cpDefinition.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY CPDefinition.displayDate DESC, CPDefinition.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.commerce.product.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.commerce.product.model.CPDefinition"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.commerce.product.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.commerce.product.model.CPDefinition"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.commerce.product.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.commerce.product.model.CPDefinition"),
			true);
	public static final long CPTAXCATEGORYID_COLUMN_BITMASK = 1L;
	public static final long COMPANYID_COLUMN_BITMASK = 2L;
	public static final long DISPLAYDATE_COLUMN_BITMASK = 4L;
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 8L;
	public static final long GROUPID_COLUMN_BITMASK = 16L;
	public static final long STATUS_COLUMN_BITMASK = 32L;
	public static final long UUID_COLUMN_BITMASK = 64L;
	public static final long CREATEDATE_COLUMN_BITMASK = 128L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CPDefinition toModel(CPDefinitionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CPDefinition model = new CPDefinitionImpl();

		model.setUuid(soapModel.getUuid());
		model.setExternalReferenceCode(soapModel.getExternalReferenceCode());
		model.setDefaultLanguageId(soapModel.getDefaultLanguageId());
		model.setCPDefinitionId(soapModel.getCPDefinitionId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setProductTypeName(soapModel.getProductTypeName());
		model.setAvailableIndividually(soapModel.isAvailableIndividually());
		model.setIgnoreSKUCombinations(soapModel.isIgnoreSKUCombinations());
		model.setShippable(soapModel.isShippable());
		model.setFreeShipping(soapModel.isFreeShipping());
		model.setShipSeparately(soapModel.isShipSeparately());
		model.setShippingExtraPrice(soapModel.getShippingExtraPrice());
		model.setWidth(soapModel.getWidth());
		model.setHeight(soapModel.getHeight());
		model.setDepth(soapModel.getDepth());
		model.setWeight(soapModel.getWeight());
		model.setCPTaxCategoryId(soapModel.getCPTaxCategoryId());
		model.setTaxExempt(soapModel.isTaxExempt());
		model.setTelcoOrElectronics(soapModel.isTelcoOrElectronics());
		model.setDDMStructureKey(soapModel.getDDMStructureKey());
		model.setPublished(soapModel.isPublished());
		model.setDisplayDate(soapModel.getDisplayDate());
		model.setExpirationDate(soapModel.getExpirationDate());
		model.setLastPublishDate(soapModel.getLastPublishDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CPDefinition> toModels(CPDefinitionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CPDefinition> models = new ArrayList<CPDefinition>(soapModels.length);

		for (CPDefinitionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.commerce.product.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.commerce.product.model.CPDefinition"));

	public CPDefinitionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _CPDefinitionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCPDefinitionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CPDefinitionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CPDefinition.class;
	}

	@Override
	public String getModelClassName() {
		return CPDefinition.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("externalReferenceCode", getExternalReferenceCode());
		attributes.put("defaultLanguageId", getDefaultLanguageId());
		attributes.put("CPDefinitionId", getCPDefinitionId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("productTypeName", getProductTypeName());
		attributes.put("availableIndividually", isAvailableIndividually());
		attributes.put("ignoreSKUCombinations", isIgnoreSKUCombinations());
		attributes.put("shippable", isShippable());
		attributes.put("freeShipping", isFreeShipping());
		attributes.put("shipSeparately", isShipSeparately());
		attributes.put("shippingExtraPrice", getShippingExtraPrice());
		attributes.put("width", getWidth());
		attributes.put("height", getHeight());
		attributes.put("depth", getDepth());
		attributes.put("weight", getWeight());
		attributes.put("CPTaxCategoryId", getCPTaxCategoryId());
		attributes.put("taxExempt", isTaxExempt());
		attributes.put("telcoOrElectronics", isTelcoOrElectronics());
		attributes.put("DDMStructureKey", getDDMStructureKey());
		attributes.put("published", isPublished());
		attributes.put("displayDate", getDisplayDate());
		attributes.put("expirationDate", getExpirationDate());
		attributes.put("lastPublishDate", getLastPublishDate());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		String externalReferenceCode = (String)attributes.get(
				"externalReferenceCode");

		if (externalReferenceCode != null) {
			setExternalReferenceCode(externalReferenceCode);
		}

		String defaultLanguageId = (String)attributes.get("defaultLanguageId");

		if (defaultLanguageId != null) {
			setDefaultLanguageId(defaultLanguageId);
		}

		Long CPDefinitionId = (Long)attributes.get("CPDefinitionId");

		if (CPDefinitionId != null) {
			setCPDefinitionId(CPDefinitionId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String productTypeName = (String)attributes.get("productTypeName");

		if (productTypeName != null) {
			setProductTypeName(productTypeName);
		}

		Boolean availableIndividually = (Boolean)attributes.get(
				"availableIndividually");

		if (availableIndividually != null) {
			setAvailableIndividually(availableIndividually);
		}

		Boolean ignoreSKUCombinations = (Boolean)attributes.get(
				"ignoreSKUCombinations");

		if (ignoreSKUCombinations != null) {
			setIgnoreSKUCombinations(ignoreSKUCombinations);
		}

		Boolean shippable = (Boolean)attributes.get("shippable");

		if (shippable != null) {
			setShippable(shippable);
		}

		Boolean freeShipping = (Boolean)attributes.get("freeShipping");

		if (freeShipping != null) {
			setFreeShipping(freeShipping);
		}

		Boolean shipSeparately = (Boolean)attributes.get("shipSeparately");

		if (shipSeparately != null) {
			setShipSeparately(shipSeparately);
		}

		Double shippingExtraPrice = (Double)attributes.get("shippingExtraPrice");

		if (shippingExtraPrice != null) {
			setShippingExtraPrice(shippingExtraPrice);
		}

		Double width = (Double)attributes.get("width");

		if (width != null) {
			setWidth(width);
		}

		Double height = (Double)attributes.get("height");

		if (height != null) {
			setHeight(height);
		}

		Double depth = (Double)attributes.get("depth");

		if (depth != null) {
			setDepth(depth);
		}

		Double weight = (Double)attributes.get("weight");

		if (weight != null) {
			setWeight(weight);
		}

		Long CPTaxCategoryId = (Long)attributes.get("CPTaxCategoryId");

		if (CPTaxCategoryId != null) {
			setCPTaxCategoryId(CPTaxCategoryId);
		}

		Boolean taxExempt = (Boolean)attributes.get("taxExempt");

		if (taxExempt != null) {
			setTaxExempt(taxExempt);
		}

		Boolean telcoOrElectronics = (Boolean)attributes.get(
				"telcoOrElectronics");

		if (telcoOrElectronics != null) {
			setTelcoOrElectronics(telcoOrElectronics);
		}

		String DDMStructureKey = (String)attributes.get("DDMStructureKey");

		if (DDMStructureKey != null) {
			setDDMStructureKey(DDMStructureKey);
		}

		Boolean published = (Boolean)attributes.get("published");

		if (published != null) {
			setPublished(published);
		}

		Date displayDate = (Date)attributes.get("displayDate");

		if (displayDate != null) {
			setDisplayDate(displayDate);
		}

		Date expirationDate = (Date)attributes.get("expirationDate");

		if (expirationDate != null) {
			setExpirationDate(expirationDate);
		}

		Date lastPublishDate = (Date)attributes.get("lastPublishDate");

		if (lastPublishDate != null) {
			setLastPublishDate(lastPublishDate);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}
	}

	@Override
	public String[] getAvailableLanguageIds() {
		List<CPDefinitionLocalization> cpDefinitionLocalizations = CPDefinitionLocalServiceUtil.getCPDefinitionLocalizations(getPrimaryKey());

		String[] availableLanguageIds = new String[cpDefinitionLocalizations.size()];

		for (int i = 0; i < availableLanguageIds.length; i++) {
			CPDefinitionLocalization cpDefinitionLocalization = cpDefinitionLocalizations.get(i);

			availableLanguageIds[i] = cpDefinitionLocalization.getLanguageId();
		}

		return availableLanguageIds;
	}

	@Override
	public String getName() {
		return getName(getDefaultLanguageId(), false);
	}

	@Override
	public String getName(String languageId) {
		return getName(languageId, true);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(new Function<String, String>() {
					@Override
					public String apply(String languageId) {
						return _getName(languageId);
					}
				}, languageId, getDefaultLanguageId());
		}

		return _getName(languageId);
	}

	@Override
	public String getNameMapAsXML() {
		return LocalizationUtil.getXml(getLanguageIdToNameMap(),
			getDefaultLanguageId(), "Name");
	}

	@Override
	public Map<String, String> getLanguageIdToNameMap() {
		Map<String, String> languageIdToNameMap = new HashMap<String, String>();

		List<CPDefinitionLocalization> cpDefinitionLocalizations = CPDefinitionLocalServiceUtil.getCPDefinitionLocalizations(getPrimaryKey());

		for (CPDefinitionLocalization cpDefinitionLocalization : cpDefinitionLocalizations) {
			languageIdToNameMap.put(cpDefinitionLocalization.getLanguageId(),
				cpDefinitionLocalization.getName());
		}

		return languageIdToNameMap;
	}

	private String _getName(String languageId) {
		CPDefinitionLocalization cpDefinitionLocalization = CPDefinitionLocalServiceUtil.fetchCPDefinitionLocalization(getPrimaryKey(),
				languageId);

		if (cpDefinitionLocalization == null) {
			return "";
		}

		return cpDefinitionLocalization.getName();
	}

	@Override
	public String getShortDescription() {
		return getShortDescription(getDefaultLanguageId(), false);
	}

	@Override
	public String getShortDescription(String languageId) {
		return getShortDescription(languageId, true);
	}

	@Override
	public String getShortDescription(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(new Function<String, String>() {
					@Override
					public String apply(String languageId) {
						return _getShortDescription(languageId);
					}
				}, languageId, getDefaultLanguageId());
		}

		return _getShortDescription(languageId);
	}

	@Override
	public String getShortDescriptionMapAsXML() {
		return LocalizationUtil.getXml(getLanguageIdToShortDescriptionMap(),
			getDefaultLanguageId(), "ShortDescription");
	}

	@Override
	public Map<String, String> getLanguageIdToShortDescriptionMap() {
		Map<String, String> languageIdToShortDescriptionMap = new HashMap<String, String>();

		List<CPDefinitionLocalization> cpDefinitionLocalizations = CPDefinitionLocalServiceUtil.getCPDefinitionLocalizations(getPrimaryKey());

		for (CPDefinitionLocalization cpDefinitionLocalization : cpDefinitionLocalizations) {
			languageIdToShortDescriptionMap.put(cpDefinitionLocalization.getLanguageId(),
				cpDefinitionLocalization.getShortDescription());
		}

		return languageIdToShortDescriptionMap;
	}

	private String _getShortDescription(String languageId) {
		CPDefinitionLocalization cpDefinitionLocalization = CPDefinitionLocalServiceUtil.fetchCPDefinitionLocalization(getPrimaryKey(),
				languageId);

		if (cpDefinitionLocalization == null) {
			return "";
		}

		return cpDefinitionLocalization.getShortDescription();
	}

	@Override
	public String getDescription() {
		return getDescription(getDefaultLanguageId(), false);
	}

	@Override
	public String getDescription(String languageId) {
		return getDescription(languageId, true);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(new Function<String, String>() {
					@Override
					public String apply(String languageId) {
						return _getDescription(languageId);
					}
				}, languageId, getDefaultLanguageId());
		}

		return _getDescription(languageId);
	}

	@Override
	public String getDescriptionMapAsXML() {
		return LocalizationUtil.getXml(getLanguageIdToDescriptionMap(),
			getDefaultLanguageId(), "Description");
	}

	@Override
	public Map<String, String> getLanguageIdToDescriptionMap() {
		Map<String, String> languageIdToDescriptionMap = new HashMap<String, String>();

		List<CPDefinitionLocalization> cpDefinitionLocalizations = CPDefinitionLocalServiceUtil.getCPDefinitionLocalizations(getPrimaryKey());

		for (CPDefinitionLocalization cpDefinitionLocalization : cpDefinitionLocalizations) {
			languageIdToDescriptionMap.put(cpDefinitionLocalization.getLanguageId(),
				cpDefinitionLocalization.getDescription());
		}

		return languageIdToDescriptionMap;
	}

	private String _getDescription(String languageId) {
		CPDefinitionLocalization cpDefinitionLocalization = CPDefinitionLocalServiceUtil.fetchCPDefinitionLocalization(getPrimaryKey(),
				languageId);

		if (cpDefinitionLocalization == null) {
			return "";
		}

		return cpDefinitionLocalization.getDescription();
	}

	@Override
	public String getMetaTitle() {
		return getMetaTitle(getDefaultLanguageId(), false);
	}

	@Override
	public String getMetaTitle(String languageId) {
		return getMetaTitle(languageId, true);
	}

	@Override
	public String getMetaTitle(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(new Function<String, String>() {
					@Override
					public String apply(String languageId) {
						return _getMetaTitle(languageId);
					}
				}, languageId, getDefaultLanguageId());
		}

		return _getMetaTitle(languageId);
	}

	@Override
	public String getMetaTitleMapAsXML() {
		return LocalizationUtil.getXml(getLanguageIdToMetaTitleMap(),
			getDefaultLanguageId(), "MetaTitle");
	}

	@Override
	public Map<String, String> getLanguageIdToMetaTitleMap() {
		Map<String, String> languageIdToMetaTitleMap = new HashMap<String, String>();

		List<CPDefinitionLocalization> cpDefinitionLocalizations = CPDefinitionLocalServiceUtil.getCPDefinitionLocalizations(getPrimaryKey());

		for (CPDefinitionLocalization cpDefinitionLocalization : cpDefinitionLocalizations) {
			languageIdToMetaTitleMap.put(cpDefinitionLocalization.getLanguageId(),
				cpDefinitionLocalization.getMetaTitle());
		}

		return languageIdToMetaTitleMap;
	}

	private String _getMetaTitle(String languageId) {
		CPDefinitionLocalization cpDefinitionLocalization = CPDefinitionLocalServiceUtil.fetchCPDefinitionLocalization(getPrimaryKey(),
				languageId);

		if (cpDefinitionLocalization == null) {
			return "";
		}

		return cpDefinitionLocalization.getMetaTitle();
	}

	@Override
	public String getMetaDescription() {
		return getMetaDescription(getDefaultLanguageId(), false);
	}

	@Override
	public String getMetaDescription(String languageId) {
		return getMetaDescription(languageId, true);
	}

	@Override
	public String getMetaDescription(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(new Function<String, String>() {
					@Override
					public String apply(String languageId) {
						return _getMetaDescription(languageId);
					}
				}, languageId, getDefaultLanguageId());
		}

		return _getMetaDescription(languageId);
	}

	@Override
	public String getMetaDescriptionMapAsXML() {
		return LocalizationUtil.getXml(getLanguageIdToMetaDescriptionMap(),
			getDefaultLanguageId(), "MetaDescription");
	}

	@Override
	public Map<String, String> getLanguageIdToMetaDescriptionMap() {
		Map<String, String> languageIdToMetaDescriptionMap = new HashMap<String, String>();

		List<CPDefinitionLocalization> cpDefinitionLocalizations = CPDefinitionLocalServiceUtil.getCPDefinitionLocalizations(getPrimaryKey());

		for (CPDefinitionLocalization cpDefinitionLocalization : cpDefinitionLocalizations) {
			languageIdToMetaDescriptionMap.put(cpDefinitionLocalization.getLanguageId(),
				cpDefinitionLocalization.getMetaDescription());
		}

		return languageIdToMetaDescriptionMap;
	}

	private String _getMetaDescription(String languageId) {
		CPDefinitionLocalization cpDefinitionLocalization = CPDefinitionLocalServiceUtil.fetchCPDefinitionLocalization(getPrimaryKey(),
				languageId);

		if (cpDefinitionLocalization == null) {
			return "";
		}

		return cpDefinitionLocalization.getMetaDescription();
	}

	@Override
	public String getMetaKeywords() {
		return getMetaKeywords(getDefaultLanguageId(), false);
	}

	@Override
	public String getMetaKeywords(String languageId) {
		return getMetaKeywords(languageId, true);
	}

	@Override
	public String getMetaKeywords(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(new Function<String, String>() {
					@Override
					public String apply(String languageId) {
						return _getMetaKeywords(languageId);
					}
				}, languageId, getDefaultLanguageId());
		}

		return _getMetaKeywords(languageId);
	}

	@Override
	public String getMetaKeywordsMapAsXML() {
		return LocalizationUtil.getXml(getLanguageIdToMetaKeywordsMap(),
			getDefaultLanguageId(), "MetaKeywords");
	}

	@Override
	public Map<String, String> getLanguageIdToMetaKeywordsMap() {
		Map<String, String> languageIdToMetaKeywordsMap = new HashMap<String, String>();

		List<CPDefinitionLocalization> cpDefinitionLocalizations = CPDefinitionLocalServiceUtil.getCPDefinitionLocalizations(getPrimaryKey());

		for (CPDefinitionLocalization cpDefinitionLocalization : cpDefinitionLocalizations) {
			languageIdToMetaKeywordsMap.put(cpDefinitionLocalization.getLanguageId(),
				cpDefinitionLocalization.getMetaKeywords());
		}

		return languageIdToMetaKeywordsMap;
	}

	private String _getMetaKeywords(String languageId) {
		CPDefinitionLocalization cpDefinitionLocalization = CPDefinitionLocalServiceUtil.fetchCPDefinitionLocalization(getPrimaryKey(),
				languageId);

		if (cpDefinitionLocalization == null) {
			return "";
		}

		return cpDefinitionLocalization.getMetaKeywords();
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		_columnBitmask |= EXTERNALREFERENCECODE_COLUMN_BITMASK;

		if (_originalExternalReferenceCode == null) {
			_originalExternalReferenceCode = _externalReferenceCode;
		}

		_externalReferenceCode = externalReferenceCode;
	}

	public String getOriginalExternalReferenceCode() {
		return GetterUtil.getString(_originalExternalReferenceCode);
	}

	@JSON
	@Override
	public String getDefaultLanguageId() {
		if (_defaultLanguageId == null) {
			return "";
		}
		else {
			return _defaultLanguageId;
		}
	}

	@Override
	public void setDefaultLanguageId(String defaultLanguageId) {
		_defaultLanguageId = defaultLanguageId;
	}

	@JSON
	@Override
	public long getCPDefinitionId() {
		return _CPDefinitionId;
	}

	@Override
	public void setCPDefinitionId(long CPDefinitionId) {
		_CPDefinitionId = CPDefinitionId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getProductTypeName() {
		if (_productTypeName == null) {
			return "";
		}
		else {
			return _productTypeName;
		}
	}

	@Override
	public void setProductTypeName(String productTypeName) {
		_productTypeName = productTypeName;
	}

	@JSON
	@Override
	public boolean getAvailableIndividually() {
		return _availableIndividually;
	}

	@JSON
	@Override
	public boolean isAvailableIndividually() {
		return _availableIndividually;
	}

	@Override
	public void setAvailableIndividually(boolean availableIndividually) {
		_availableIndividually = availableIndividually;
	}

	@JSON
	@Override
	public boolean getIgnoreSKUCombinations() {
		return _ignoreSKUCombinations;
	}

	@JSON
	@Override
	public boolean isIgnoreSKUCombinations() {
		return _ignoreSKUCombinations;
	}

	@Override
	public void setIgnoreSKUCombinations(boolean ignoreSKUCombinations) {
		_ignoreSKUCombinations = ignoreSKUCombinations;
	}

	@JSON
	@Override
	public boolean getShippable() {
		return _shippable;
	}

	@JSON
	@Override
	public boolean isShippable() {
		return _shippable;
	}

	@Override
	public void setShippable(boolean shippable) {
		_shippable = shippable;
	}

	@JSON
	@Override
	public boolean getFreeShipping() {
		return _freeShipping;
	}

	@JSON
	@Override
	public boolean isFreeShipping() {
		return _freeShipping;
	}

	@Override
	public void setFreeShipping(boolean freeShipping) {
		_freeShipping = freeShipping;
	}

	@JSON
	@Override
	public boolean getShipSeparately() {
		return _shipSeparately;
	}

	@JSON
	@Override
	public boolean isShipSeparately() {
		return _shipSeparately;
	}

	@Override
	public void setShipSeparately(boolean shipSeparately) {
		_shipSeparately = shipSeparately;
	}

	@JSON
	@Override
	public double getShippingExtraPrice() {
		return _shippingExtraPrice;
	}

	@Override
	public void setShippingExtraPrice(double shippingExtraPrice) {
		_shippingExtraPrice = shippingExtraPrice;
	}

	@JSON
	@Override
	public double getWidth() {
		return _width;
	}

	@Override
	public void setWidth(double width) {
		_width = width;
	}

	@JSON
	@Override
	public double getHeight() {
		return _height;
	}

	@Override
	public void setHeight(double height) {
		_height = height;
	}

	@JSON
	@Override
	public double getDepth() {
		return _depth;
	}

	@Override
	public void setDepth(double depth) {
		_depth = depth;
	}

	@JSON
	@Override
	public double getWeight() {
		return _weight;
	}

	@Override
	public void setWeight(double weight) {
		_weight = weight;
	}

	@JSON
	@Override
	public long getCPTaxCategoryId() {
		return _CPTaxCategoryId;
	}

	@Override
	public void setCPTaxCategoryId(long CPTaxCategoryId) {
		_columnBitmask |= CPTAXCATEGORYID_COLUMN_BITMASK;

		if (!_setOriginalCPTaxCategoryId) {
			_setOriginalCPTaxCategoryId = true;

			_originalCPTaxCategoryId = _CPTaxCategoryId;
		}

		_CPTaxCategoryId = CPTaxCategoryId;
	}

	public long getOriginalCPTaxCategoryId() {
		return _originalCPTaxCategoryId;
	}

	@JSON
	@Override
	public boolean getTaxExempt() {
		return _taxExempt;
	}

	@JSON
	@Override
	public boolean isTaxExempt() {
		return _taxExempt;
	}

	@Override
	public void setTaxExempt(boolean taxExempt) {
		_taxExempt = taxExempt;
	}

	@JSON
	@Override
	public boolean getTelcoOrElectronics() {
		return _telcoOrElectronics;
	}

	@JSON
	@Override
	public boolean isTelcoOrElectronics() {
		return _telcoOrElectronics;
	}

	@Override
	public void setTelcoOrElectronics(boolean telcoOrElectronics) {
		_telcoOrElectronics = telcoOrElectronics;
	}

	@JSON
	@Override
	public String getDDMStructureKey() {
		if (_DDMStructureKey == null) {
			return "";
		}
		else {
			return _DDMStructureKey;
		}
	}

	@Override
	public void setDDMStructureKey(String DDMStructureKey) {
		_DDMStructureKey = DDMStructureKey;
	}

	@JSON
	@Override
	public boolean getPublished() {
		return _published;
	}

	@JSON
	@Override
	public boolean isPublished() {
		return _published;
	}

	@Override
	public void setPublished(boolean published) {
		_published = published;
	}

	@JSON
	@Override
	public Date getDisplayDate() {
		return _displayDate;
	}

	@Override
	public void setDisplayDate(Date displayDate) {
		_columnBitmask = -1L;

		if (_originalDisplayDate == null) {
			_originalDisplayDate = _displayDate;
		}

		_displayDate = displayDate;
	}

	public Date getOriginalDisplayDate() {
		return _originalDisplayDate;
	}

	@JSON
	@Override
	public Date getExpirationDate() {
		return _expirationDate;
	}

	@Override
	public void setExpirationDate(Date expirationDate) {
		_expirationDate = expirationDate;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_lastPublishDate = lastPublishDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				CPDefinition.class.getName()));
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {
		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry = com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.fetchEntry(getModelClassName(),
				getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler = getTrashHandler();

		if (Validator.isNotNull(trashHandler.getContainerModelClassName(
						getPrimaryKey()))) {
			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException nsme) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler = com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.getTrashHandler(trashHandler.getContainerModelClassName(
							containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	* @deprecated As of Judson (7.1.x), with no direct replacement
	*/
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler = getTrashHandler();

		if ((trashHandler == null) ||
				Validator.isNull(trashHandler.getContainerModelClassName(
						getPrimaryKey()))) {
			return false;
		}

		try {
			ContainerModel containerModel = trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception e) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry = com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.fetchEntry(getModelClassName(),
				getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry = com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.fetchEntry(getModelClassName(),
				getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CPDefinition.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CPDefinition toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CPDefinition)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CPDefinitionImpl cpDefinitionImpl = new CPDefinitionImpl();

		cpDefinitionImpl.setUuid(getUuid());
		cpDefinitionImpl.setExternalReferenceCode(getExternalReferenceCode());
		cpDefinitionImpl.setDefaultLanguageId(getDefaultLanguageId());
		cpDefinitionImpl.setCPDefinitionId(getCPDefinitionId());
		cpDefinitionImpl.setGroupId(getGroupId());
		cpDefinitionImpl.setCompanyId(getCompanyId());
		cpDefinitionImpl.setUserId(getUserId());
		cpDefinitionImpl.setUserName(getUserName());
		cpDefinitionImpl.setCreateDate(getCreateDate());
		cpDefinitionImpl.setModifiedDate(getModifiedDate());
		cpDefinitionImpl.setProductTypeName(getProductTypeName());
		cpDefinitionImpl.setAvailableIndividually(isAvailableIndividually());
		cpDefinitionImpl.setIgnoreSKUCombinations(isIgnoreSKUCombinations());
		cpDefinitionImpl.setShippable(isShippable());
		cpDefinitionImpl.setFreeShipping(isFreeShipping());
		cpDefinitionImpl.setShipSeparately(isShipSeparately());
		cpDefinitionImpl.setShippingExtraPrice(getShippingExtraPrice());
		cpDefinitionImpl.setWidth(getWidth());
		cpDefinitionImpl.setHeight(getHeight());
		cpDefinitionImpl.setDepth(getDepth());
		cpDefinitionImpl.setWeight(getWeight());
		cpDefinitionImpl.setCPTaxCategoryId(getCPTaxCategoryId());
		cpDefinitionImpl.setTaxExempt(isTaxExempt());
		cpDefinitionImpl.setTelcoOrElectronics(isTelcoOrElectronics());
		cpDefinitionImpl.setDDMStructureKey(getDDMStructureKey());
		cpDefinitionImpl.setPublished(isPublished());
		cpDefinitionImpl.setDisplayDate(getDisplayDate());
		cpDefinitionImpl.setExpirationDate(getExpirationDate());
		cpDefinitionImpl.setLastPublishDate(getLastPublishDate());
		cpDefinitionImpl.setStatus(getStatus());
		cpDefinitionImpl.setStatusByUserId(getStatusByUserId());
		cpDefinitionImpl.setStatusByUserName(getStatusByUserName());
		cpDefinitionImpl.setStatusDate(getStatusDate());

		cpDefinitionImpl.resetOriginalValues();

		return cpDefinitionImpl;
	}

	@Override
	public int compareTo(CPDefinition cpDefinition) {
		int value = 0;

		value = DateUtil.compareTo(getDisplayDate(),
				cpDefinition.getDisplayDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(getCreateDate(), cpDefinition.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CPDefinition)) {
			return false;
		}

		CPDefinition cpDefinition = (CPDefinition)obj;

		long primaryKey = cpDefinition.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CPDefinitionModelImpl cpDefinitionModelImpl = this;

		cpDefinitionModelImpl._originalUuid = cpDefinitionModelImpl._uuid;

		cpDefinitionModelImpl._originalExternalReferenceCode = cpDefinitionModelImpl._externalReferenceCode;

		cpDefinitionModelImpl._originalGroupId = cpDefinitionModelImpl._groupId;

		cpDefinitionModelImpl._setOriginalGroupId = false;

		cpDefinitionModelImpl._originalCompanyId = cpDefinitionModelImpl._companyId;

		cpDefinitionModelImpl._setOriginalCompanyId = false;

		cpDefinitionModelImpl._setModifiedDate = false;

		cpDefinitionModelImpl._originalCPTaxCategoryId = cpDefinitionModelImpl._CPTaxCategoryId;

		cpDefinitionModelImpl._setOriginalCPTaxCategoryId = false;

		cpDefinitionModelImpl._originalDisplayDate = cpDefinitionModelImpl._displayDate;

		cpDefinitionModelImpl._originalStatus = cpDefinitionModelImpl._status;

		cpDefinitionModelImpl._setOriginalStatus = false;

		cpDefinitionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CPDefinition> toCacheModel() {
		CPDefinitionCacheModel cpDefinitionCacheModel = new CPDefinitionCacheModel();

		cpDefinitionCacheModel.uuid = getUuid();

		String uuid = cpDefinitionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			cpDefinitionCacheModel.uuid = null;
		}

		cpDefinitionCacheModel.externalReferenceCode = getExternalReferenceCode();

		String externalReferenceCode = cpDefinitionCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
				(externalReferenceCode.length() == 0)) {
			cpDefinitionCacheModel.externalReferenceCode = null;
		}

		cpDefinitionCacheModel.defaultLanguageId = getDefaultLanguageId();

		String defaultLanguageId = cpDefinitionCacheModel.defaultLanguageId;

		if ((defaultLanguageId != null) && (defaultLanguageId.length() == 0)) {
			cpDefinitionCacheModel.defaultLanguageId = null;
		}

		cpDefinitionCacheModel.CPDefinitionId = getCPDefinitionId();

		cpDefinitionCacheModel.groupId = getGroupId();

		cpDefinitionCacheModel.companyId = getCompanyId();

		cpDefinitionCacheModel.userId = getUserId();

		cpDefinitionCacheModel.userName = getUserName();

		String userName = cpDefinitionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cpDefinitionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cpDefinitionCacheModel.createDate = createDate.getTime();
		}
		else {
			cpDefinitionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cpDefinitionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cpDefinitionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cpDefinitionCacheModel.productTypeName = getProductTypeName();

		String productTypeName = cpDefinitionCacheModel.productTypeName;

		if ((productTypeName != null) && (productTypeName.length() == 0)) {
			cpDefinitionCacheModel.productTypeName = null;
		}

		cpDefinitionCacheModel.availableIndividually = isAvailableIndividually();

		cpDefinitionCacheModel.ignoreSKUCombinations = isIgnoreSKUCombinations();

		cpDefinitionCacheModel.shippable = isShippable();

		cpDefinitionCacheModel.freeShipping = isFreeShipping();

		cpDefinitionCacheModel.shipSeparately = isShipSeparately();

		cpDefinitionCacheModel.shippingExtraPrice = getShippingExtraPrice();

		cpDefinitionCacheModel.width = getWidth();

		cpDefinitionCacheModel.height = getHeight();

		cpDefinitionCacheModel.depth = getDepth();

		cpDefinitionCacheModel.weight = getWeight();

		cpDefinitionCacheModel.CPTaxCategoryId = getCPTaxCategoryId();

		cpDefinitionCacheModel.taxExempt = isTaxExempt();

		cpDefinitionCacheModel.telcoOrElectronics = isTelcoOrElectronics();

		cpDefinitionCacheModel.DDMStructureKey = getDDMStructureKey();

		String DDMStructureKey = cpDefinitionCacheModel.DDMStructureKey;

		if ((DDMStructureKey != null) && (DDMStructureKey.length() == 0)) {
			cpDefinitionCacheModel.DDMStructureKey = null;
		}

		cpDefinitionCacheModel.published = isPublished();

		Date displayDate = getDisplayDate();

		if (displayDate != null) {
			cpDefinitionCacheModel.displayDate = displayDate.getTime();
		}
		else {
			cpDefinitionCacheModel.displayDate = Long.MIN_VALUE;
		}

		Date expirationDate = getExpirationDate();

		if (expirationDate != null) {
			cpDefinitionCacheModel.expirationDate = expirationDate.getTime();
		}
		else {
			cpDefinitionCacheModel.expirationDate = Long.MIN_VALUE;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			cpDefinitionCacheModel.lastPublishDate = lastPublishDate.getTime();
		}
		else {
			cpDefinitionCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		cpDefinitionCacheModel.status = getStatus();

		cpDefinitionCacheModel.statusByUserId = getStatusByUserId();

		cpDefinitionCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = cpDefinitionCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			cpDefinitionCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			cpDefinitionCacheModel.statusDate = statusDate.getTime();
		}
		else {
			cpDefinitionCacheModel.statusDate = Long.MIN_VALUE;
		}

		return cpDefinitionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(67);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", externalReferenceCode=");
		sb.append(getExternalReferenceCode());
		sb.append(", defaultLanguageId=");
		sb.append(getDefaultLanguageId());
		sb.append(", CPDefinitionId=");
		sb.append(getCPDefinitionId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", productTypeName=");
		sb.append(getProductTypeName());
		sb.append(", availableIndividually=");
		sb.append(isAvailableIndividually());
		sb.append(", ignoreSKUCombinations=");
		sb.append(isIgnoreSKUCombinations());
		sb.append(", shippable=");
		sb.append(isShippable());
		sb.append(", freeShipping=");
		sb.append(isFreeShipping());
		sb.append(", shipSeparately=");
		sb.append(isShipSeparately());
		sb.append(", shippingExtraPrice=");
		sb.append(getShippingExtraPrice());
		sb.append(", width=");
		sb.append(getWidth());
		sb.append(", height=");
		sb.append(getHeight());
		sb.append(", depth=");
		sb.append(getDepth());
		sb.append(", weight=");
		sb.append(getWeight());
		sb.append(", CPTaxCategoryId=");
		sb.append(getCPTaxCategoryId());
		sb.append(", taxExempt=");
		sb.append(isTaxExempt());
		sb.append(", telcoOrElectronics=");
		sb.append(isTelcoOrElectronics());
		sb.append(", DDMStructureKey=");
		sb.append(getDDMStructureKey());
		sb.append(", published=");
		sb.append(isPublished());
		sb.append(", displayDate=");
		sb.append(getDisplayDate());
		sb.append(", expirationDate=");
		sb.append(getExpirationDate());
		sb.append(", lastPublishDate=");
		sb.append(getLastPublishDate());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(103);

		sb.append("<model><model-name>");
		sb.append("com.liferay.commerce.product.model.CPDefinition");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>externalReferenceCode</column-name><column-value><![CDATA[");
		sb.append(getExternalReferenceCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>defaultLanguageId</column-name><column-value><![CDATA[");
		sb.append(getDefaultLanguageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CPDefinitionId</column-name><column-value><![CDATA[");
		sb.append(getCPDefinitionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productTypeName</column-name><column-value><![CDATA[");
		sb.append(getProductTypeName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>availableIndividually</column-name><column-value><![CDATA[");
		sb.append(isAvailableIndividually());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ignoreSKUCombinations</column-name><column-value><![CDATA[");
		sb.append(isIgnoreSKUCombinations());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shippable</column-name><column-value><![CDATA[");
		sb.append(isShippable());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>freeShipping</column-name><column-value><![CDATA[");
		sb.append(isFreeShipping());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipSeparately</column-name><column-value><![CDATA[");
		sb.append(isShipSeparately());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shippingExtraPrice</column-name><column-value><![CDATA[");
		sb.append(getShippingExtraPrice());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>width</column-name><column-value><![CDATA[");
		sb.append(getWidth());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>height</column-name><column-value><![CDATA[");
		sb.append(getHeight());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>depth</column-name><column-value><![CDATA[");
		sb.append(getDepth());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>weight</column-name><column-value><![CDATA[");
		sb.append(getWeight());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CPTaxCategoryId</column-name><column-value><![CDATA[");
		sb.append(getCPTaxCategoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taxExempt</column-name><column-value><![CDATA[");
		sb.append(isTaxExempt());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telcoOrElectronics</column-name><column-value><![CDATA[");
		sb.append(isTelcoOrElectronics());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DDMStructureKey</column-name><column-value><![CDATA[");
		sb.append(getDDMStructureKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>published</column-name><column-value><![CDATA[");
		sb.append(isPublished());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>displayDate</column-name><column-value><![CDATA[");
		sb.append(getDisplayDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>expirationDate</column-name><column-value><![CDATA[");
		sb.append(getExpirationDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastPublishDate</column-name><column-value><![CDATA[");
		sb.append(getLastPublishDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CPDefinition.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CPDefinition.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private String _externalReferenceCode;
	private String _originalExternalReferenceCode;
	private String _defaultLanguageId;
	private long _CPDefinitionId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _productTypeName;
	private boolean _availableIndividually;
	private boolean _ignoreSKUCombinations;
	private boolean _shippable;
	private boolean _freeShipping;
	private boolean _shipSeparately;
	private double _shippingExtraPrice;
	private double _width;
	private double _height;
	private double _depth;
	private double _weight;
	private long _CPTaxCategoryId;
	private long _originalCPTaxCategoryId;
	private boolean _setOriginalCPTaxCategoryId;
	private boolean _taxExempt;
	private boolean _telcoOrElectronics;
	private String _DDMStructureKey;
	private boolean _published;
	private Date _displayDate;
	private Date _originalDisplayDate;
	private Date _expirationDate;
	private Date _lastPublishDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private CPDefinition _escapedModel;
}