/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.product.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.product.model.CPRuleChannelRel;
import com.liferay.commerce.product.model.CPRuleChannelRelModel;
import com.liferay.commerce.product.model.CPRuleChannelRelSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CPRuleChannelRel service. Represents a row in the &quot;CPRuleChannelRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CPRuleChannelRelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPRuleChannelRelImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CPRuleChannelRelImpl
 * @see CPRuleChannelRel
 * @see CPRuleChannelRelModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CPRuleChannelRelModelImpl extends BaseModelImpl<CPRuleChannelRel>
	implements CPRuleChannelRelModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cp rule channel rel model instance should use the {@link CPRuleChannelRel} interface instead.
	 */
	public static final String TABLE_NAME = "CPRuleChannelRel";
	public static final Object[][] TABLE_COLUMNS = {
			{ "CPRuleChannelRelId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "CPRuleId", Types.BIGINT },
			{ "commerceChannelId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("CPRuleChannelRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CPRuleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commerceChannelId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table CPRuleChannelRel (CPRuleChannelRelId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,CPRuleId LONG,commerceChannelId LONG)";
	public static final String TABLE_SQL_DROP = "drop table CPRuleChannelRel";
	public static final String ORDER_BY_JPQL = " ORDER BY cpRuleChannelRel.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY CPRuleChannelRel.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.commerce.product.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.commerce.product.model.CPRuleChannelRel"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.commerce.product.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.commerce.product.model.CPRuleChannelRel"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.commerce.product.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.commerce.product.model.CPRuleChannelRel"),
			true);
	public static final long CPRULEID_COLUMN_BITMASK = 1L;
	public static final long COMMERCECHANNELID_COLUMN_BITMASK = 2L;
	public static final long CREATEDATE_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CPRuleChannelRel toModel(CPRuleChannelRelSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CPRuleChannelRel model = new CPRuleChannelRelImpl();

		model.setCPRuleChannelRelId(soapModel.getCPRuleChannelRelId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCPRuleId(soapModel.getCPRuleId());
		model.setCommerceChannelId(soapModel.getCommerceChannelId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CPRuleChannelRel> toModels(
		CPRuleChannelRelSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CPRuleChannelRel> models = new ArrayList<CPRuleChannelRel>(soapModels.length);

		for (CPRuleChannelRelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.commerce.product.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.commerce.product.model.CPRuleChannelRel"));

	public CPRuleChannelRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _CPRuleChannelRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCPRuleChannelRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CPRuleChannelRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CPRuleChannelRel.class;
	}

	@Override
	public String getModelClassName() {
		return CPRuleChannelRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("CPRuleChannelRelId", getCPRuleChannelRelId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("CPRuleId", getCPRuleId());
		attributes.put("commerceChannelId", getCommerceChannelId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long CPRuleChannelRelId = (Long)attributes.get("CPRuleChannelRelId");

		if (CPRuleChannelRelId != null) {
			setCPRuleChannelRelId(CPRuleChannelRelId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long CPRuleId = (Long)attributes.get("CPRuleId");

		if (CPRuleId != null) {
			setCPRuleId(CPRuleId);
		}

		Long commerceChannelId = (Long)attributes.get("commerceChannelId");

		if (commerceChannelId != null) {
			setCommerceChannelId(commerceChannelId);
		}
	}

	@JSON
	@Override
	public long getCPRuleChannelRelId() {
		return _CPRuleChannelRelId;
	}

	@Override
	public void setCPRuleChannelRelId(long CPRuleChannelRelId) {
		_CPRuleChannelRelId = CPRuleChannelRelId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCPRuleId() {
		return _CPRuleId;
	}

	@Override
	public void setCPRuleId(long CPRuleId) {
		_columnBitmask |= CPRULEID_COLUMN_BITMASK;

		if (!_setOriginalCPRuleId) {
			_setOriginalCPRuleId = true;

			_originalCPRuleId = _CPRuleId;
		}

		_CPRuleId = CPRuleId;
	}

	public long getOriginalCPRuleId() {
		return _originalCPRuleId;
	}

	@JSON
	@Override
	public long getCommerceChannelId() {
		return _commerceChannelId;
	}

	@Override
	public void setCommerceChannelId(long commerceChannelId) {
		_columnBitmask |= COMMERCECHANNELID_COLUMN_BITMASK;

		if (!_setOriginalCommerceChannelId) {
			_setOriginalCommerceChannelId = true;

			_originalCommerceChannelId = _commerceChannelId;
		}

		_commerceChannelId = commerceChannelId;
	}

	public long getOriginalCommerceChannelId() {
		return _originalCommerceChannelId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CPRuleChannelRel.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CPRuleChannelRel toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CPRuleChannelRel)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CPRuleChannelRelImpl cpRuleChannelRelImpl = new CPRuleChannelRelImpl();

		cpRuleChannelRelImpl.setCPRuleChannelRelId(getCPRuleChannelRelId());
		cpRuleChannelRelImpl.setGroupId(getGroupId());
		cpRuleChannelRelImpl.setCompanyId(getCompanyId());
		cpRuleChannelRelImpl.setUserId(getUserId());
		cpRuleChannelRelImpl.setUserName(getUserName());
		cpRuleChannelRelImpl.setCreateDate(getCreateDate());
		cpRuleChannelRelImpl.setModifiedDate(getModifiedDate());
		cpRuleChannelRelImpl.setCPRuleId(getCPRuleId());
		cpRuleChannelRelImpl.setCommerceChannelId(getCommerceChannelId());

		cpRuleChannelRelImpl.resetOriginalValues();

		return cpRuleChannelRelImpl;
	}

	@Override
	public int compareTo(CPRuleChannelRel cpRuleChannelRel) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				cpRuleChannelRel.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CPRuleChannelRel)) {
			return false;
		}

		CPRuleChannelRel cpRuleChannelRel = (CPRuleChannelRel)obj;

		long primaryKey = cpRuleChannelRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CPRuleChannelRelModelImpl cpRuleChannelRelModelImpl = this;

		cpRuleChannelRelModelImpl._setModifiedDate = false;

		cpRuleChannelRelModelImpl._originalCPRuleId = cpRuleChannelRelModelImpl._CPRuleId;

		cpRuleChannelRelModelImpl._setOriginalCPRuleId = false;

		cpRuleChannelRelModelImpl._originalCommerceChannelId = cpRuleChannelRelModelImpl._commerceChannelId;

		cpRuleChannelRelModelImpl._setOriginalCommerceChannelId = false;

		cpRuleChannelRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CPRuleChannelRel> toCacheModel() {
		CPRuleChannelRelCacheModel cpRuleChannelRelCacheModel = new CPRuleChannelRelCacheModel();

		cpRuleChannelRelCacheModel.CPRuleChannelRelId = getCPRuleChannelRelId();

		cpRuleChannelRelCacheModel.groupId = getGroupId();

		cpRuleChannelRelCacheModel.companyId = getCompanyId();

		cpRuleChannelRelCacheModel.userId = getUserId();

		cpRuleChannelRelCacheModel.userName = getUserName();

		String userName = cpRuleChannelRelCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cpRuleChannelRelCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cpRuleChannelRelCacheModel.createDate = createDate.getTime();
		}
		else {
			cpRuleChannelRelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cpRuleChannelRelCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cpRuleChannelRelCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cpRuleChannelRelCacheModel.CPRuleId = getCPRuleId();

		cpRuleChannelRelCacheModel.commerceChannelId = getCommerceChannelId();

		return cpRuleChannelRelCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{CPRuleChannelRelId=");
		sb.append(getCPRuleChannelRelId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", CPRuleId=");
		sb.append(getCPRuleId());
		sb.append(", commerceChannelId=");
		sb.append(getCommerceChannelId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.liferay.commerce.product.model.CPRuleChannelRel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>CPRuleChannelRelId</column-name><column-value><![CDATA[");
		sb.append(getCPRuleChannelRelId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CPRuleId</column-name><column-value><![CDATA[");
		sb.append(getCPRuleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>commerceChannelId</column-name><column-value><![CDATA[");
		sb.append(getCommerceChannelId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CPRuleChannelRel.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CPRuleChannelRel.class, ModelWrapper.class
		};
	private long _CPRuleChannelRelId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _CPRuleId;
	private long _originalCPRuleId;
	private boolean _setOriginalCPRuleId;
	private long _commerceChannelId;
	private long _originalCommerceChannelId;
	private boolean _setOriginalCommerceChannelId;
	private long _columnBitmask;
	private CPRuleChannelRel _escapedModel;
}