/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.product.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.product.model.CPRuleUserSegmentRel;
import com.liferay.commerce.product.model.CPRuleUserSegmentRelModel;
import com.liferay.commerce.product.model.CPRuleUserSegmentRelSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CPRuleUserSegmentRel service. Represents a row in the &quot;CPRuleUserSegmentRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CPRuleUserSegmentRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPRuleUserSegmentRelImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CPRuleUserSegmentRelImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CPRuleUserSegmentRelModelImpl
	extends BaseModelImpl<CPRuleUserSegmentRel>
	implements CPRuleUserSegmentRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cp rule user segment rel model instance should use the <code>CPRuleUserSegmentRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "CPRuleUserSegmentRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"CPRuleUserSegmentRelId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"CPRuleId", Types.BIGINT},
		{"commerceUserSegmentEntryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("CPRuleUserSegmentRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CPRuleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commerceUserSegmentEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CPRuleUserSegmentRel (CPRuleUserSegmentRelId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,CPRuleId LONG,commerceUserSegmentEntryId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table CPRuleUserSegmentRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY cpRuleUserSegmentRel.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CPRuleUserSegmentRel.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.product.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.commerce.product.model.CPRuleUserSegmentRel"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.product.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.commerce.product.model.CPRuleUserSegmentRel"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.product.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.commerce.product.model.CPRuleUserSegmentRel"),
		true);

	public static final long CPRULEID_COLUMN_BITMASK = 1L;

	public static final long COMMERCEUSERSEGMENTENTRYID_COLUMN_BITMASK = 2L;

	public static final long CREATEDATE_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CPRuleUserSegmentRel toModel(
		CPRuleUserSegmentRelSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		CPRuleUserSegmentRel model = new CPRuleUserSegmentRelImpl();

		model.setCPRuleUserSegmentRelId(soapModel.getCPRuleUserSegmentRelId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCPRuleId(soapModel.getCPRuleId());
		model.setCommerceUserSegmentEntryId(
			soapModel.getCommerceUserSegmentEntryId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CPRuleUserSegmentRel> toModels(
		CPRuleUserSegmentRelSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<CPRuleUserSegmentRel> models = new ArrayList<CPRuleUserSegmentRel>(
			soapModels.length);

		for (CPRuleUserSegmentRelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.commerce.product.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.commerce.product.model.CPRuleUserSegmentRel"));

	public CPRuleUserSegmentRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _CPRuleUserSegmentRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCPRuleUserSegmentRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CPRuleUserSegmentRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CPRuleUserSegmentRel.class;
	}

	@Override
	public String getModelClassName() {
		return CPRuleUserSegmentRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CPRuleUserSegmentRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CPRuleUserSegmentRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPRuleUserSegmentRel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CPRuleUserSegmentRel)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CPRuleUserSegmentRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CPRuleUserSegmentRel, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CPRuleUserSegmentRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CPRuleUserSegmentRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CPRuleUserSegmentRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<CPRuleUserSegmentRel, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CPRuleUserSegmentRel, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CPRuleUserSegmentRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CPRuleUserSegmentRel, Object>>();
		Map<String, BiConsumer<CPRuleUserSegmentRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<CPRuleUserSegmentRel, ?>>();

		attributeGetterFunctions.put(
			"CPRuleUserSegmentRelId",
			new Function<CPRuleUserSegmentRel, Object>() {

				@Override
				public Object apply(CPRuleUserSegmentRel cpRuleUserSegmentRel) {
					return cpRuleUserSegmentRel.getCPRuleUserSegmentRelId();
				}

			});
		attributeSetterBiConsumers.put(
			"CPRuleUserSegmentRelId",
			new BiConsumer<CPRuleUserSegmentRel, Object>() {

				@Override
				public void accept(
					CPRuleUserSegmentRel cpRuleUserSegmentRel,
					Object CPRuleUserSegmentRelId) {

					cpRuleUserSegmentRel.setCPRuleUserSegmentRelId(
						(Long)CPRuleUserSegmentRelId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<CPRuleUserSegmentRel, Object>() {

				@Override
				public Object apply(CPRuleUserSegmentRel cpRuleUserSegmentRel) {
					return cpRuleUserSegmentRel.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<CPRuleUserSegmentRel, Object>() {

				@Override
				public void accept(
					CPRuleUserSegmentRel cpRuleUserSegmentRel, Object groupId) {

					cpRuleUserSegmentRel.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CPRuleUserSegmentRel, Object>() {

				@Override
				public Object apply(CPRuleUserSegmentRel cpRuleUserSegmentRel) {
					return cpRuleUserSegmentRel.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CPRuleUserSegmentRel, Object>() {

				@Override
				public void accept(
					CPRuleUserSegmentRel cpRuleUserSegmentRel,
					Object companyId) {

					cpRuleUserSegmentRel.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<CPRuleUserSegmentRel, Object>() {

				@Override
				public Object apply(CPRuleUserSegmentRel cpRuleUserSegmentRel) {
					return cpRuleUserSegmentRel.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<CPRuleUserSegmentRel, Object>() {

				@Override
				public void accept(
					CPRuleUserSegmentRel cpRuleUserSegmentRel, Object userId) {

					cpRuleUserSegmentRel.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<CPRuleUserSegmentRel, Object>() {

				@Override
				public Object apply(CPRuleUserSegmentRel cpRuleUserSegmentRel) {
					return cpRuleUserSegmentRel.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<CPRuleUserSegmentRel, Object>() {

				@Override
				public void accept(
					CPRuleUserSegmentRel cpRuleUserSegmentRel,
					Object userName) {

					cpRuleUserSegmentRel.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CPRuleUserSegmentRel, Object>() {

				@Override
				public Object apply(CPRuleUserSegmentRel cpRuleUserSegmentRel) {
					return cpRuleUserSegmentRel.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CPRuleUserSegmentRel, Object>() {

				@Override
				public void accept(
					CPRuleUserSegmentRel cpRuleUserSegmentRel,
					Object createDate) {

					cpRuleUserSegmentRel.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CPRuleUserSegmentRel, Object>() {

				@Override
				public Object apply(CPRuleUserSegmentRel cpRuleUserSegmentRel) {
					return cpRuleUserSegmentRel.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CPRuleUserSegmentRel, Object>() {

				@Override
				public void accept(
					CPRuleUserSegmentRel cpRuleUserSegmentRel,
					Object modifiedDate) {

					cpRuleUserSegmentRel.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"CPRuleId",
			new Function<CPRuleUserSegmentRel, Object>() {

				@Override
				public Object apply(CPRuleUserSegmentRel cpRuleUserSegmentRel) {
					return cpRuleUserSegmentRel.getCPRuleId();
				}

			});
		attributeSetterBiConsumers.put(
			"CPRuleId",
			new BiConsumer<CPRuleUserSegmentRel, Object>() {

				@Override
				public void accept(
					CPRuleUserSegmentRel cpRuleUserSegmentRel,
					Object CPRuleId) {

					cpRuleUserSegmentRel.setCPRuleId((Long)CPRuleId);
				}

			});
		attributeGetterFunctions.put(
			"commerceUserSegmentEntryId",
			new Function<CPRuleUserSegmentRel, Object>() {

				@Override
				public Object apply(CPRuleUserSegmentRel cpRuleUserSegmentRel) {
					return cpRuleUserSegmentRel.getCommerceUserSegmentEntryId();
				}

			});
		attributeSetterBiConsumers.put(
			"commerceUserSegmentEntryId",
			new BiConsumer<CPRuleUserSegmentRel, Object>() {

				@Override
				public void accept(
					CPRuleUserSegmentRel cpRuleUserSegmentRel,
					Object commerceUserSegmentEntryId) {

					cpRuleUserSegmentRel.setCommerceUserSegmentEntryId(
						(Long)commerceUserSegmentEntryId);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getCPRuleUserSegmentRelId() {
		return _CPRuleUserSegmentRelId;
	}

	@Override
	public void setCPRuleUserSegmentRelId(long CPRuleUserSegmentRelId) {
		_CPRuleUserSegmentRelId = CPRuleUserSegmentRelId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCPRuleId() {
		return _CPRuleId;
	}

	@Override
	public void setCPRuleId(long CPRuleId) {
		_columnBitmask |= CPRULEID_COLUMN_BITMASK;

		if (!_setOriginalCPRuleId) {
			_setOriginalCPRuleId = true;

			_originalCPRuleId = _CPRuleId;
		}

		_CPRuleId = CPRuleId;
	}

	public long getOriginalCPRuleId() {
		return _originalCPRuleId;
	}

	@JSON
	@Override
	public long getCommerceUserSegmentEntryId() {
		return _commerceUserSegmentEntryId;
	}

	@Override
	public void setCommerceUserSegmentEntryId(long commerceUserSegmentEntryId) {
		_columnBitmask |= COMMERCEUSERSEGMENTENTRYID_COLUMN_BITMASK;

		if (!_setOriginalCommerceUserSegmentEntryId) {
			_setOriginalCommerceUserSegmentEntryId = true;

			_originalCommerceUserSegmentEntryId = _commerceUserSegmentEntryId;
		}

		_commerceUserSegmentEntryId = commerceUserSegmentEntryId;
	}

	public long getOriginalCommerceUserSegmentEntryId() {
		return _originalCommerceUserSegmentEntryId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CPRuleUserSegmentRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CPRuleUserSegmentRel toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CPRuleUserSegmentRel)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CPRuleUserSegmentRelImpl cpRuleUserSegmentRelImpl =
			new CPRuleUserSegmentRelImpl();

		cpRuleUserSegmentRelImpl.setCPRuleUserSegmentRelId(
			getCPRuleUserSegmentRelId());
		cpRuleUserSegmentRelImpl.setGroupId(getGroupId());
		cpRuleUserSegmentRelImpl.setCompanyId(getCompanyId());
		cpRuleUserSegmentRelImpl.setUserId(getUserId());
		cpRuleUserSegmentRelImpl.setUserName(getUserName());
		cpRuleUserSegmentRelImpl.setCreateDate(getCreateDate());
		cpRuleUserSegmentRelImpl.setModifiedDate(getModifiedDate());
		cpRuleUserSegmentRelImpl.setCPRuleId(getCPRuleId());
		cpRuleUserSegmentRelImpl.setCommerceUserSegmentEntryId(
			getCommerceUserSegmentEntryId());

		cpRuleUserSegmentRelImpl.resetOriginalValues();

		return cpRuleUserSegmentRelImpl;
	}

	@Override
	public int compareTo(CPRuleUserSegmentRel cpRuleUserSegmentRel) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), cpRuleUserSegmentRel.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CPRuleUserSegmentRel)) {
			return false;
		}

		CPRuleUserSegmentRel cpRuleUserSegmentRel = (CPRuleUserSegmentRel)obj;

		long primaryKey = cpRuleUserSegmentRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CPRuleUserSegmentRelModelImpl cpRuleUserSegmentRelModelImpl = this;

		cpRuleUserSegmentRelModelImpl._setModifiedDate = false;

		cpRuleUserSegmentRelModelImpl._originalCPRuleId =
			cpRuleUserSegmentRelModelImpl._CPRuleId;

		cpRuleUserSegmentRelModelImpl._setOriginalCPRuleId = false;

		cpRuleUserSegmentRelModelImpl._originalCommerceUserSegmentEntryId =
			cpRuleUserSegmentRelModelImpl._commerceUserSegmentEntryId;

		cpRuleUserSegmentRelModelImpl._setOriginalCommerceUserSegmentEntryId =
			false;

		cpRuleUserSegmentRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CPRuleUserSegmentRel> toCacheModel() {
		CPRuleUserSegmentRelCacheModel cpRuleUserSegmentRelCacheModel =
			new CPRuleUserSegmentRelCacheModel();

		cpRuleUserSegmentRelCacheModel.CPRuleUserSegmentRelId =
			getCPRuleUserSegmentRelId();

		cpRuleUserSegmentRelCacheModel.groupId = getGroupId();

		cpRuleUserSegmentRelCacheModel.companyId = getCompanyId();

		cpRuleUserSegmentRelCacheModel.userId = getUserId();

		cpRuleUserSegmentRelCacheModel.userName = getUserName();

		String userName = cpRuleUserSegmentRelCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cpRuleUserSegmentRelCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cpRuleUserSegmentRelCacheModel.createDate = createDate.getTime();
		}
		else {
			cpRuleUserSegmentRelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cpRuleUserSegmentRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			cpRuleUserSegmentRelCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cpRuleUserSegmentRelCacheModel.CPRuleId = getCPRuleId();

		cpRuleUserSegmentRelCacheModel.commerceUserSegmentEntryId =
			getCommerceUserSegmentEntryId();

		return cpRuleUserSegmentRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CPRuleUserSegmentRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CPRuleUserSegmentRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPRuleUserSegmentRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((CPRuleUserSegmentRel)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CPRuleUserSegmentRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CPRuleUserSegmentRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPRuleUserSegmentRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((CPRuleUserSegmentRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		CPRuleUserSegmentRel.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		CPRuleUserSegmentRel.class, ModelWrapper.class
	};

	private long _CPRuleUserSegmentRelId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _CPRuleId;
	private long _originalCPRuleId;
	private boolean _setOriginalCPRuleId;
	private long _commerceUserSegmentEntryId;
	private long _originalCommerceUserSegmentEntryId;
	private boolean _setOriginalCommerceUserSegmentEntryId;
	private long _columnBitmask;
	private CPRuleUserSegmentRel _escapedModel;

}