/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.product.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.product.model.CPSubscriptionCycleEntry;
import com.liferay.commerce.product.model.CPSubscriptionCycleEntryModel;
import com.liferay.commerce.product.model.CPSubscriptionCycleEntrySoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CPSubscriptionCycleEntry service. Represents a row in the &quot;CPSubscriptionCycleEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CPSubscriptionCycleEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPSubscriptionCycleEntryImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CPSubscriptionCycleEntryImpl
 * @see CPSubscriptionCycleEntry
 * @see CPSubscriptionCycleEntryModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CPSubscriptionCycleEntryModelImpl extends BaseModelImpl<CPSubscriptionCycleEntry>
	implements CPSubscriptionCycleEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cp subscription cycle entry model instance should use the {@link CPSubscriptionCycleEntry} interface instead.
	 */
	public static final String TABLE_NAME = "CPSubscriptionCycleEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "CPSubscriptionCycleEntryId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "CPSubscriptionEntryId", Types.BIGINT },
			{ "commerceOrderItemId", Types.BIGINT },
			{ "renew", Types.BOOLEAN }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CPSubscriptionCycleEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CPSubscriptionEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commerceOrderItemId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("renew", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE = "create table CPSubscriptionCycleEntry (uuid_ VARCHAR(75) null,CPSubscriptionCycleEntryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,CPSubscriptionEntryId LONG,commerceOrderItemId LONG,renew BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table CPSubscriptionCycleEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY cpSubscriptionCycleEntry.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY CPSubscriptionCycleEntry.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.commerce.product.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.commerce.product.model.CPSubscriptionCycleEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.commerce.product.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.commerce.product.model.CPSubscriptionCycleEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.commerce.product.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.commerce.product.model.CPSubscriptionCycleEntry"),
			true);
	public static final long CPSUBSCRIPTIONENTRYID_COLUMN_BITMASK = 1L;
	public static final long COMMERCEORDERITEMID_COLUMN_BITMASK = 2L;
	public static final long COMPANYID_COLUMN_BITMASK = 4L;
	public static final long GROUPID_COLUMN_BITMASK = 8L;
	public static final long UUID_COLUMN_BITMASK = 16L;
	public static final long CREATEDATE_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CPSubscriptionCycleEntry toModel(
		CPSubscriptionCycleEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CPSubscriptionCycleEntry model = new CPSubscriptionCycleEntryImpl();

		model.setUuid(soapModel.getUuid());
		model.setCPSubscriptionCycleEntryId(soapModel.getCPSubscriptionCycleEntryId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCPSubscriptionEntryId(soapModel.getCPSubscriptionEntryId());
		model.setCommerceOrderItemId(soapModel.getCommerceOrderItemId());
		model.setRenew(soapModel.isRenew());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CPSubscriptionCycleEntry> toModels(
		CPSubscriptionCycleEntrySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CPSubscriptionCycleEntry> models = new ArrayList<CPSubscriptionCycleEntry>(soapModels.length);

		for (CPSubscriptionCycleEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.commerce.product.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.commerce.product.model.CPSubscriptionCycleEntry"));

	public CPSubscriptionCycleEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _CPSubscriptionCycleEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCPSubscriptionCycleEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CPSubscriptionCycleEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CPSubscriptionCycleEntry.class;
	}

	@Override
	public String getModelClassName() {
		return CPSubscriptionCycleEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("CPSubscriptionCycleEntryId",
			getCPSubscriptionCycleEntryId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("CPSubscriptionEntryId", getCPSubscriptionEntryId());
		attributes.put("commerceOrderItemId", getCommerceOrderItemId());
		attributes.put("renew", isRenew());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long CPSubscriptionCycleEntryId = (Long)attributes.get(
				"CPSubscriptionCycleEntryId");

		if (CPSubscriptionCycleEntryId != null) {
			setCPSubscriptionCycleEntryId(CPSubscriptionCycleEntryId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long CPSubscriptionEntryId = (Long)attributes.get(
				"CPSubscriptionEntryId");

		if (CPSubscriptionEntryId != null) {
			setCPSubscriptionEntryId(CPSubscriptionEntryId);
		}

		Long commerceOrderItemId = (Long)attributes.get("commerceOrderItemId");

		if (commerceOrderItemId != null) {
			setCommerceOrderItemId(commerceOrderItemId);
		}

		Boolean renew = (Boolean)attributes.get("renew");

		if (renew != null) {
			setRenew(renew);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getCPSubscriptionCycleEntryId() {
		return _CPSubscriptionCycleEntryId;
	}

	@Override
	public void setCPSubscriptionCycleEntryId(long CPSubscriptionCycleEntryId) {
		_CPSubscriptionCycleEntryId = CPSubscriptionCycleEntryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCPSubscriptionEntryId() {
		return _CPSubscriptionEntryId;
	}

	@Override
	public void setCPSubscriptionEntryId(long CPSubscriptionEntryId) {
		_columnBitmask |= CPSUBSCRIPTIONENTRYID_COLUMN_BITMASK;

		if (!_setOriginalCPSubscriptionEntryId) {
			_setOriginalCPSubscriptionEntryId = true;

			_originalCPSubscriptionEntryId = _CPSubscriptionEntryId;
		}

		_CPSubscriptionEntryId = CPSubscriptionEntryId;
	}

	public long getOriginalCPSubscriptionEntryId() {
		return _originalCPSubscriptionEntryId;
	}

	@JSON
	@Override
	public long getCommerceOrderItemId() {
		return _commerceOrderItemId;
	}

	@Override
	public void setCommerceOrderItemId(long commerceOrderItemId) {
		_columnBitmask |= COMMERCEORDERITEMID_COLUMN_BITMASK;

		if (!_setOriginalCommerceOrderItemId) {
			_setOriginalCommerceOrderItemId = true;

			_originalCommerceOrderItemId = _commerceOrderItemId;
		}

		_commerceOrderItemId = commerceOrderItemId;
	}

	public long getOriginalCommerceOrderItemId() {
		return _originalCommerceOrderItemId;
	}

	@JSON
	@Override
	public boolean getRenew() {
		return _renew;
	}

	@JSON
	@Override
	public boolean isRenew() {
		return _renew;
	}

	@Override
	public void setRenew(boolean renew) {
		_renew = renew;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				CPSubscriptionCycleEntry.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CPSubscriptionCycleEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CPSubscriptionCycleEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CPSubscriptionCycleEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CPSubscriptionCycleEntryImpl cpSubscriptionCycleEntryImpl = new CPSubscriptionCycleEntryImpl();

		cpSubscriptionCycleEntryImpl.setUuid(getUuid());
		cpSubscriptionCycleEntryImpl.setCPSubscriptionCycleEntryId(getCPSubscriptionCycleEntryId());
		cpSubscriptionCycleEntryImpl.setGroupId(getGroupId());
		cpSubscriptionCycleEntryImpl.setCompanyId(getCompanyId());
		cpSubscriptionCycleEntryImpl.setUserId(getUserId());
		cpSubscriptionCycleEntryImpl.setUserName(getUserName());
		cpSubscriptionCycleEntryImpl.setCreateDate(getCreateDate());
		cpSubscriptionCycleEntryImpl.setModifiedDate(getModifiedDate());
		cpSubscriptionCycleEntryImpl.setCPSubscriptionEntryId(getCPSubscriptionEntryId());
		cpSubscriptionCycleEntryImpl.setCommerceOrderItemId(getCommerceOrderItemId());
		cpSubscriptionCycleEntryImpl.setRenew(isRenew());

		cpSubscriptionCycleEntryImpl.resetOriginalValues();

		return cpSubscriptionCycleEntryImpl;
	}

	@Override
	public int compareTo(CPSubscriptionCycleEntry cpSubscriptionCycleEntry) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				cpSubscriptionCycleEntry.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CPSubscriptionCycleEntry)) {
			return false;
		}

		CPSubscriptionCycleEntry cpSubscriptionCycleEntry = (CPSubscriptionCycleEntry)obj;

		long primaryKey = cpSubscriptionCycleEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CPSubscriptionCycleEntryModelImpl cpSubscriptionCycleEntryModelImpl = this;

		cpSubscriptionCycleEntryModelImpl._originalUuid = cpSubscriptionCycleEntryModelImpl._uuid;

		cpSubscriptionCycleEntryModelImpl._originalGroupId = cpSubscriptionCycleEntryModelImpl._groupId;

		cpSubscriptionCycleEntryModelImpl._setOriginalGroupId = false;

		cpSubscriptionCycleEntryModelImpl._originalCompanyId = cpSubscriptionCycleEntryModelImpl._companyId;

		cpSubscriptionCycleEntryModelImpl._setOriginalCompanyId = false;

		cpSubscriptionCycleEntryModelImpl._setModifiedDate = false;

		cpSubscriptionCycleEntryModelImpl._originalCPSubscriptionEntryId = cpSubscriptionCycleEntryModelImpl._CPSubscriptionEntryId;

		cpSubscriptionCycleEntryModelImpl._setOriginalCPSubscriptionEntryId = false;

		cpSubscriptionCycleEntryModelImpl._originalCommerceOrderItemId = cpSubscriptionCycleEntryModelImpl._commerceOrderItemId;

		cpSubscriptionCycleEntryModelImpl._setOriginalCommerceOrderItemId = false;

		cpSubscriptionCycleEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CPSubscriptionCycleEntry> toCacheModel() {
		CPSubscriptionCycleEntryCacheModel cpSubscriptionCycleEntryCacheModel = new CPSubscriptionCycleEntryCacheModel();

		cpSubscriptionCycleEntryCacheModel.uuid = getUuid();

		String uuid = cpSubscriptionCycleEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			cpSubscriptionCycleEntryCacheModel.uuid = null;
		}

		cpSubscriptionCycleEntryCacheModel.CPSubscriptionCycleEntryId = getCPSubscriptionCycleEntryId();

		cpSubscriptionCycleEntryCacheModel.groupId = getGroupId();

		cpSubscriptionCycleEntryCacheModel.companyId = getCompanyId();

		cpSubscriptionCycleEntryCacheModel.userId = getUserId();

		cpSubscriptionCycleEntryCacheModel.userName = getUserName();

		String userName = cpSubscriptionCycleEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cpSubscriptionCycleEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cpSubscriptionCycleEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			cpSubscriptionCycleEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cpSubscriptionCycleEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cpSubscriptionCycleEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cpSubscriptionCycleEntryCacheModel.CPSubscriptionEntryId = getCPSubscriptionEntryId();

		cpSubscriptionCycleEntryCacheModel.commerceOrderItemId = getCommerceOrderItemId();

		cpSubscriptionCycleEntryCacheModel.renew = isRenew();

		return cpSubscriptionCycleEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", CPSubscriptionCycleEntryId=");
		sb.append(getCPSubscriptionCycleEntryId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", CPSubscriptionEntryId=");
		sb.append(getCPSubscriptionEntryId());
		sb.append(", commerceOrderItemId=");
		sb.append(getCommerceOrderItemId());
		sb.append(", renew=");
		sb.append(isRenew());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.liferay.commerce.product.model.CPSubscriptionCycleEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CPSubscriptionCycleEntryId</column-name><column-value><![CDATA[");
		sb.append(getCPSubscriptionCycleEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CPSubscriptionEntryId</column-name><column-value><![CDATA[");
		sb.append(getCPSubscriptionEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>commerceOrderItemId</column-name><column-value><![CDATA[");
		sb.append(getCommerceOrderItemId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>renew</column-name><column-value><![CDATA[");
		sb.append(isRenew());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CPSubscriptionCycleEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CPSubscriptionCycleEntry.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _CPSubscriptionCycleEntryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _CPSubscriptionEntryId;
	private long _originalCPSubscriptionEntryId;
	private boolean _setOriginalCPSubscriptionEntryId;
	private long _commerceOrderItemId;
	private long _originalCommerceOrderItemId;
	private boolean _setOriginalCommerceOrderItemId;
	private boolean _renew;
	private long _columnBitmask;
	private CPSubscriptionCycleEntry _escapedModel;
}