create table CommerceVirtualOrderItem (
	uuid_ VARCHAR(75) null,
	commerceVirtualOrderItemId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	commerceOrderItemId LONG,
	fileEntryId LONG,
	url VARCHAR(75) null,
	activationStatus INTEGER,
	duration LONG,
	usages INTEGER,
	maxUsages INTEGER,
	active_ BOOLEAN,
	startDate DATE null,
	endDate DATE null
);