apiDir: "../headless-commerce-machine-learning-api/src/main/java"
apiPackagePath: "com.liferay.headless.commerce.machine.learning"
application:
    baseURI: "/headless-commerce-machine-learning"
    className: "HeadlessCommerceMachineLEarningApplication"
    name: "Liferay.Headless.Commerce.Machine.Learning"
author: "Riccardo Ferrari"