apiDir: "../headless-commerce-admin-site-setting-api/src/main/java"
apiPackagePath: "com.liferay.headless.commerce.admin.site.setting"
application:
    baseURI: "/headless-commerce-admin-site-setting"
    className: "HeadlessCommerceAdminSiteSettingApplication"
    name: "Liferay.Headless.Commerce.Admin.Site.Setting"
author: "Zoltán Takács"