apiDir: "../commerce-bom-rest-api/src/main/java"
apiPackagePath: "com.liferay.commerce.bom.rest"
application:
    baseURI: "/commerce-bom"
    className: "CommerceBOMApplication"
    name: "Liferay.Commerce.BOM"
author: "Alessio Antonio Rendina"